### ISSUE TITLE
 Feature Request: Add possibility to make new post with custom date-time

### ISSUE THREAD

**Issue by zlaxy** [redmatrix/hubzilla#1033]
I want to move many entries from my old blog to Hubzilla. I would like to set original date for this posts.
Is it possible to add a field for setting a specific date of publication during editing post?

**Comment by git-marijus** [comment]
I think we could send an invite once while creating the chatroom. We have a similar functionality for wikis and files already. We could ad a switch labeled `Create a status post for this chat`

**Comment by zotlabs** [comment]
This is possible at post creation time using the  'Delayed Posting' feature. You can set the post date (either forwards or backwards) during post creation. This is not available when editing an existing post because the posts would have already been delivered. 

The feature requires an account level of 2; which you can find on your settings/account page; followed by activating the Delayed Posting feature at settings/features -> Post Composition Features

**Comment by zlaxy** [comment]
> The feature requires an account level of 2

Thanks, i changed account level and found it, it works good.
I'll close this issue.
