### ISSUE TITLE
'New' activity network stream missing options from posts

### ISSUE THREAD

**Issue by Thndr** [redmatrix/hubzilla#1036]
When viewing the 'New' network stream it acts like you're not logged in and doesn't provide options such as Like, emoji reaction, or some other features the other stream filters provide.

**Comment by zotlabs** [comment]
This is intentional. What you are viewing is raw activity items as they were received, devoid of any conversational context. It is the same as 'search' in this regard. Comments and likes and posts are all intermingled, shown as they were received in reverse order. 

A link is provided to view each item in its original conversational context and interact with it normally.

**Comment by Thndr** [comment]
Ah, I guess I misunderstood that intention of the feature.
Makes sense along with the option to go to the post itself being available anyway.
