### ISSUE TITLE
Stylesheet: couldn't see Categories.

### ISSUE THREAD

**Issue by zlaxy** [redmatrix/hubzilla#1047]
I enabled Additional Features -> Post/Comment Tools -> Post Categories
But can't add categories to my posts.
Also searched mention about Categories in documentation - i didn't find it.

Please explain how to use this feature, add it to docs.

**Comment by elvecio** [comment]
usually, when they are enabled, you should see 3 spaces to write.
1 small for the title
1 small for the categories
1 bigger for the post

Once you have created the post with  'categories' , you should see, on the side (in your page), the "category", similar to  tags, in order to visit the post as often as you want.

**Comment by zlaxy** [comment]
Oh, yes, it's obvious, this does not need documentation...
But my default browser view (i use dark theme) was:
![2018-04-07-075638_1280x800_scrot](https://user-images.githubusercontent.com/19224533/38451502-abb4fb3c-3a39-11e8-839f-98b144798e6b.png)
after changing colour finally this field was discovered:
![2018-04-07-075650_1280x800_scrot](https://user-images.githubusercontent.com/19224533/38451505-ba1b5d06-3a39-11e8-9904-f4dad8346cbf.png)
Thanks for explanation.


Maybe it will be better to change style of Categories field element to the same to Title/Post?

**Comment by git-marijus** [comment]
The alternate schemas do not have a maintainer at the moment. We kind of keep the dark schema on life support. The simple_* schemas are mostly not usable anymore since the last major UI updates.
They will be removed with the next release if nobody steps up and maintains them.

A pullrequest to dev branch with your fixes would be very appreciated!

**Comment by zlaxy** [comment]
I found that this problem related only to my dark gtk-theme/browser (Firefox). I have installed Chrome, this category-field looks fine in Chrome:
![2018-04-08-150430_1280x800_scrot](https://user-images.githubusercontent.com/19224533/38467283-00f09696-3b3f-11e8-92fe-501486691b1f.png)
But i prefer using Firefox, i inspect this element and found that problem in css style... It was string 19 in file `/library/bootstrap-tagsinput`:
`  background-color: transparent;`
After commenting it, Category field became visible and usable:
![2018-04-08-150425_1280x800_scrot](https://user-images.githubusercontent.com/19224533/38467400-a499a7aa-3b40-11e8-9ad7-4e45cda0bdb4.png)
I think that this line is superfluous. With default style themes it does not matter, with custom browser theme it make tagsinput element not visible.

Please, tell me how best to make a pull request:
delete or comment out this line from css file?

**Comment by zlaxy** [comment]
with 
```
.bootstrap-tagsinput input {
    color: $font_colour;
}
```
in `view/theme/redbasic/css/style.css`:

![2018-04-11-235334_1280x800_scrot](https://user-images.githubusercontent.com/19224533/38643655-8d994558-3de6-11e8-97fb-f9b88f564346.png)

**Comment by zlaxy** [comment]
I checked it now, this problem similar to dark gtk-theme in Firefox browser (not related to other browsers). I use LXDE, it uses GTK2. I think it will happens with any other GTK2 desktop environment. Also i set all settings of Firefox to defaults (theme, css tricks etc), and just changing various GTK themes by LXapperance tool:
![2018-04-12-103244_1280x800_scrot](https://user-images.githubusercontent.com/19224533/38663390-5362cf5e-3e3f-11e8-8fe6-3f0b6e861715.png)
- Everything is fine with any light theme.
![2018-04-12-105354_1280x800_scrot](https://user-images.githubusercontent.com/19224533/38663641-09669772-3e40-11e8-8b7c-314be3093439.png)
- Category field (also tags field, but i don't use tags in Hubzilla) with my Adwaita-dark theme.
![2018-04-12-105409_1280x800_scrot](https://user-images.githubusercontent.com/19224533/38663681-2d28c450-3e40-11e8-9bb5-235485cd265b.png)
- with another dark theme, 'elementary Dark', font and background merge too.
I have no installed another dark GTK themes, but i think with them will happen the same because of the inheritance of system colors by the Firefox browser.

**Comment by git-marijus** [comment]
Thanks for your explanation and testing. I think the correct fix for the issue is to assign color and background-color to all input fields and textareas etc. It looks weird to just have those fields reflect the gtk theme. Assigning the mentioned colors in css will prevent gtk to set the gtk theme colors.
