### ISSUE TITLE
autosave: comments should be saved by thread-id

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#1069]
Having a comment autosaved an then clicking in another commentbox will populate the new commentbox with text from another thread otherwise. This behaviour is prone to error.

**Comment by zotlabs** [comment]
Let me merge this with my previous issue #1068 -

While autosave is very useful and works pretty much as advertised, the comment handling is a bit weak. I think we need to not only save them by thread-id, but also load them during page load/update so that the correct comment box is opened.

As an additional feature (lower priority) put a timestamp on saved comments (and maybe posts also) where they will expire after 48 hours. I've been known to leave a page as a means of deciding not to post the comment I've spent the last 30 minutes working on. It's one click instead of click to focus, ctrl-a, ctrl-x. I'll need to adjust that behaviour but we probably don't want unfinished and abandoned comments piling up in localstorage

**Comment by zotlabs** [comment]
I believe I have it all working except for expiration.
