### ISSUE TITLE
Own name in front of each notification

### ISSUE THREAD

**Issue by hfroese** [redmatrix/hubzilla#1070]
Own name in front of each notification hides more relevant information.
Is there any way to disable this?

![20180411-1600](https://user-images.githubusercontent.com/1968490/38621559-63acfe28-3da1-11e8-9bc1-7e258b882c87.jpg)

**Comment by git-marijus** [comment]
Yes, @mrjive is also plagued by this issue.

We remove those already for english language because in this language we know for sure how the sentence is built. If we would remove them for every language it could pretty easy mess up some translations.

The only (easy) solution i see is to remove it completely. This would have the side-effect that in the  e-mail notification you will not be able to see which of your channels is addressed.

I will leave this for the community to decide.

**Comment by hfroese** [comment]
Much better:

![20180414-1916](https://user-images.githubusercontent.com/1968490/38770779-63331e68-4018-11e8-80b7-82bace8bf3d9.jpg)

Thanks 👍
