### ISSUE TITLE
List of locations on connection edit page are multiplied for Diaspora connections

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#111]
See screenshot:

![hubzilla-issue110](https://cloud.githubusercontent.com/assets/3049892/10859098/7294e8b8-7f5a-11e5-99cd-fa36a46e17f8.png)

**Comment by git-marijus** [comment]
We shoud probably still check why we have duplicate entries for one diaspora address...

**Comment by redmatrix** [comment]
I didn't restrict by network originally because what it's important to report here is the undesirable case when a connection has no hublocs. This is also why the messages says "available locations" and not "alternate locations". This is a necessary window into the hubloc table. RSS connections should have 'none'. It's an anomaly if folks in other networks have 'none' (and this situation has happened several times recently; it's a bugger to track). But likewise they shouldn't have a list of duplicates. I've just filtered by hubloc_deleted and site_dead which was on my list of things to fix already and which did result in duplicates in some cases. This may remove some or all of them. Otherwise I'm sort of in favour of bringing back the display for all networks as this can be used by ordinary folks with no special DB access to note that there's an anomaly which probably needs attention and fixing. Otherwise we just get reports that something doesn't work and there's no way for them to know that the hublocs for that channel are mangled or non-existent. There's also no way for the admin to easily determine this information, which is why I added it to this page. We would like for this situation to not exist, but as long as it does exist I'm in favour of providing as much info as possible. In this particular case I'd like to see if filtering deleted/dead nodes from the list changes the output. If it doesn't, there's actually a problem at this site with one or more Diaspora connections which may require attention. 

@jeroenpraat - any clues in your DB as to why all these hublocs exist for the same Diaspora webbie? Do  any of them have hubloc_deleted set?

**Comment by git-marijus** [comment]
Reverted filtering by network. I only have one d* contact for testing it has two identical (except for the hubloc_id) entries in hubloc.

**Comment by jeroenpraat** [comment]
@redmatrix There are indeed many hubloc entries for the same Diaspora webbie. All Diaspora accounts seems to suffer from this. *hubloc_deleted* are **all** set to 0. But, only the one with the most recent *hubloc_updated* date have *hubloc_flags* set to 0, all other ones are set to 1. So all webbies have one record with hubloc_flags* set to 0 (the most recent updated).

**Comment by jeroenpraat** [comment]
Tested, fixed.
