### ISSUE TITLE
500 Internal Server Error during registration porecess with specific emails

### ISSUE THREAD

**Issue by zlaxy** [redmatrix/hubzilla#1154]
When i try to register new user with any@yandex.ru email on my hub it returns 500 Internal Server Error
https://ussr.win/register
There webserver logs:
```
[Thu May 03 14:41:30.707792 2018] [fcgid:warn] [pid 4186] [client ip:port] mod_fcgid: read data timeout in 31 seconds, referer: https://ussr.win/register
[Thu May 03 14:41:30.707837 2018] [core:error] [pid 4186] [client ip:port] End of script output before headers: index.php, referer: https://ussr.win/register
```
When i try any@gmail.com email during registration - everything goes ok.

I tried another hubs: with myemail@yandex.ru:
https://peacepharm.org/register - returns `Not a valid email address`
https://dacha.xmpp.moe/register - everything goes ok, this hub accepted this email, i received email and deny registration
and tried some other hubs - it was ok...

I tried enable/disable phpmailer - 1.1 plugin, it did not change anything.

Why my server returns error on some specific emails during registration?

**Comment by zotlabs** [comment]
As it turns out PHPMailer has a built-in timeout of 5 minutes. I just tried to connect to the SMTP port at yandex.ru and could not get a protocol greeting after waiting for about 10 minutes. 

Not certain the best approach to take here. If we can't deliver mail reliably, the account can't validate. The application probably shouldn't fail, but this is the first time we've been made aware that this timeout exists.

**Comment by zlaxy** [comment]
@zotlabs I tried to track this error and found out that hangs on the image to the function `z_dns_check()`. And specifically on: `dns_get_record()`
I began to check on my server by making a file test.php with the call of this function:
```
<?php                                                                      
var_dump(dns_get_record("gmail.com"));
?>
```
It returns array with DNS records...
Then i try `dns_get_record("notregisteredomain83765.com")` - it returns small array without any NS records.
Finally i tried `dns_get_record("yandex.ru")` - and result 500 Internal Server Error after timeout...
It is very interesting that after trying `dns_get_record("ya.ru")` (ya.ru is the short domain of russian yandex) - it reterned array with records, but `dns_get_record("yandex.com")` and `dns_get_record("yandex.ua")` hangs too (as yandex.ru). I checked - all these yandex domains use different DNS. I can not explain this behavior in any way.
It's Debian 9 server and system nslookup command works fine with all of this domains. Problem only with php dns_get_record().

Also i noticed article `If you see an error during database setup that DNS lookup failed` in `/install/INSTALL.txt` file, and add `App::$config['system']['do_not_check_dns'] = 1;` to `.htconfig.php` - after that registration for the domain yandex has earned.

This problem is not unique to my server. For example, on this hub, the check does not hang, but simply returns the false result:
https://peacepharm.org/register/email_check.json?f=&email=anyemail%40yandex.ru
https://peacepharm.org/register/email_check.json?f=&email=anyemail%40yandex.com
https://peacepharm.org/register/email_check.json?f=&email=anyemail%40yandex.ua
and correct result with `ya.ru` like my server:
https://peacepharm.org/register/email_check.json?f=&email=anyemail%40ya.ru
Probably, this problem is typical for other servers and for other domains. So just turning off dns checking on my server is not the best solution...

So i suggest using the function checkdnsrr() in z_dns_check(): `checkdnsrr($domain)` or `checkdnsrr($domain,"MX")`. On my server it works perfectly with any domains.

If you agree, i will make an appropriate pull request.

**Comment by zlaxy** [comment]
Also, i now found that the mandatory indication of the second parameter does not cause the function dns_get_record() to hanging:
`var_dump(dns_get_record("yandex.ru", DNS_MX));` - returns the corresponding array. This is another way to solve this problem.

**Comment by zotlabs** [comment]
We used to check MX records for email domains but this causes issues for BSD platforms. Their PHP libraries only support  looking for 'any' DNS response and not specific DNS attributes. So perhaps this should be a site configuration. Thew problem we have is that some DNS checks are done during system installation before there is any way to set a configuration; so we opted to just look for the existence of any DNS record so that BSD would work. Otherwise Hubzilla could not be used at all on BSD platforms.

So perhaps we need to go the other way - provide system installation using any DNS response, but have a configuration which allows sites with working DNS to probe just MX records. Or as you've suggested, check for any response first, and then check for an MX record if that fails. You still might get a timeout, but the next query would go through. that would probably work for the BSD folks, since they'll get a valid response on the first query and won't try the second - which would give them a failure.

**Comment by zlaxy** [comment]
@zotlabs I made pull request witl little additions https://github.com/redmatrix/hubzilla/pull/1187 ... I found that checking for the second parameter is not done (commented out), although the reference from the problem function goes exactly with this second parameter. The call to a function z_dns_check() with the second parameter only occurs from function validate_email(). So the added condition is logically suitable for this check.

Such dns check processing should not change any existing functionality, while it solves the problem on my server, and maybe on peacepharm.org and some others...

**Comment by zlaxy** [comment]
@zotlabs Could you please check the work of `z_dns_check()` with this commit on MacOS / FreeBSD? 
If the problem remains, then I think this will work in any case:
```
	if ($check_mx)
		return(checkdnsrr($h));
	else
		return((@dns_get_record($h) || filter_var($h, FILTER_VALIDATE_IP)) ? true : false);
```

**Comment by zlaxy** [comment]
With this commit https://github.com/redmatrix/hubzilla/commit/cd4454100b41f384148d0c1ebdaf6e64d629b0e1 everything works fine, thanks.
