### ISSUE TITLE
URL Rewrite Check fails

### ISSUE THREAD

**Issue by pubmania** [redmatrix/hubzilla#1172]
Hi,
I have followed steps as closely as possible to homeinstall script except I can't run it directly because while I do have Debian 9 on the system, I have an existing Apache Server running and will be using virtual hosts and I use certbot for getting Let's Encrypt certificates and enfocing https which is where I think my issue is coming from....

As can be seen on attached screenshot, I am getting the error that suggests URL Rewrite check is failing:
![selection_014](https://user-images.githubusercontent.com/1966557/39969512-6dbe4290-56d4-11e8-8f9e-603818c6c438.png)

I have tried the following without success:
I have removed htaccess, added it back, modified the rules from script on the apache conf file while keeping and excluding the rules added by Let's Encrypt and this error just wont go away.

Any advice on what I can do to get past this will be hugely appreciated.

**Comment by zotlabs** [comment]
Check for "AllowOverride All" in the site Apache configuration file and Apache mod_rewrite installed and restart Apache after changing anything.

If all of those things have been done, we have occasionally seen false positives for this check because of 

1. SSL configuration
2. DNS/firewall restrictions which prevent a site talking to itself. 

From a command line on the server, try 'curl https://...../test/rewrite' and it should pinpoint what's going on. You should get a text 'ok' response iirc. The browser may not be a sufficient test in this case but curl should exercise it in the same way as the server code.

**Comment by pubmania** [comment]
Hi Thanks for the response. I added the following in both site.conf and site-le-ssl.conf:

```        <Directory /var/www/html/hubzilla>
                AllowOverride All
        </Directory>
```
then I ran the curl https://.../test/rewrite and it worked
![selection_015](https://user-images.githubusercontent.com/1966557/39973091-20a5dfd8-5713-11e8-8b82-6c14648118db.png)
