### ISSUE TITLE
Do not attempt to deliver unsigned Diaspora "likes" by turning them into fake reshare activities by a Diaspora compatible signer 

### ISSUE THREAD

**Issue by annando** [redmatrix/hubzilla#147]
I know that there is an explanation why likes on comments are transmitted as text. But likes on starting posts are part of the Diaspora protocol and could be transmitted regularly.

**Comment by redmatrix** [comment]
This should have been fixed about 2-3 weeks ago. Possible you're just seeing these from sites that haven't updated.

**Comment by annando** [comment]
You can see it here: https://pirati.ca/display/0bb266c2c16072373e36a4f94a93f8dfbd5d4c1093d87060f9b77b817d81b888@macgirvin.com

The site seems to be https://zothub.com

**Comment by redmatrix** [comment]
Hubzilla fix backported to redmatrix 

[master 11ae34f] hubzilla issue 147 (this is a redmatrix issue)

**Comment by zotlabs** [comment]
Will be closing this but want to document what is happening before doing so. The Diaspora protocol does not allow comments or likes that are unsigned by the Diaspora protocol. In Hubzilla (and redmatrix before it), the Diaspora protocol is an optional addon. Some conversation members may not have Diaspora installed and therefore any comments/likes they author will not be shown in Diaspora. Conversation participants from third party services such as GNU-social are completely out of luck. 

This issue is a couple of years old. We've tried various solutions for the fact that Diaspora was not designed as a multi-protocol service and simply does not federate well with anything but its own protocol. The original solution was referenced in this bug - we turned the likes/comments into "wall-to-wall" or "fake reshare" activities which are signed by the conversation owner. This met a lot of disapproval on the Diaspora/Friendica side - even though it kept the conversations intact and displayed all the activities from all the participants to all the other participants, regardless of what protocol they used.

In recent releases the act of creating Diaspora compatible "fake reshare" comments is an option that is available to the owner channel. They can enable it,  or disable it if they want Diaspora to discard the unsigned comments rather than transmit these"ugly" activities. We will not transmit unsigned likes at all because of the open hostility to trying to federate these different services (even amongst other "federated services" as noted in this issue). This constitutes message/information loss, but it isn't our bug. 

The correct solution is to fix Diaspora (and other "walled garden" protocols) so that we don't need to resort to these brutal hacks to get messages (likes/comments, etc.) to all the conversation members across network boundaries.
