### ISSUE TITLE
No work register

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/hubzilla#153]
Site > http://hubzilla.ml/register

no work register.

update github :s

**Comment by redmatrix** [comment]
You may have conflicting settings for system.register_policy. This is normal. 

In your config file it appears that it may be set to REGISTER_OPEN (which is the initial system default), but in the database, it appears to be set to REGISTER_CLOSED. Setting the value in the databse  happens when you save the settings from the Admin -> Site page. The value in the database always takes precedence if there is a conflict. If registration is closed on your site we redirect to other public sites where somebody may be able to register. 

Please change this setting using the admin site settings to the setting you desire. This will set it correctly in the database. After it is set in the database, the setting from the config file is no longer used. If this is REGISTER_CLOSED or answering "No" to "Does this site allow new member registration?", it will not be possible to register on this site. You will instead see a list of public sites that (usually) allow registration.

**Comment by royalterra** [comment]
that web no open at all . I imagine you can close this thread

**Comment by mama21mama** [comment]
No work

$a->config['system']['register_policy'] = REGISTER_APPROVE;

There is something you can do for sql?

**Comment by mama21mama** [comment]
WORK
