### ISSUE TITLE
oEmbed leaks insecure data

### ISSUE THREAD

**Issue by kenrestivo** [redmatrix/hubzilla#164]
Via @royalterra in comment on https://github.com/redmatrix/hubzilla/issues/162
```
The Plugin also pull Profile Images with not https from twitter and make the HUB insecure
```

**Comment by redmatrix** [comment]
I don't believe we are currently pulling anything from Twitter. The plugin crosspost *to* Twitter. If you're seeing insecure data in your stream from Twitter it's like coming through the oEmbed service and we aren't proxying it through sslify (only img tags) because as you may recall this caused an issue with videos. .

**Comment by kenrestivo** [comment]
It sounds like this might be a wontfix, or rather a cantfix?

**Comment by royalterra** [comment]
Look is easy to fix when you setup the connector from the user administration to twitter remove the link pulling the twitter Picture profile and put any twitter logo.
That solve the problem
