### ISSUE TITLE
New profile pictures don't load after changing them.

### ISSUE THREAD

**Issue by kenrestivo** [redmatrix/hubzilla#165]
After updating a new profile picture, the old one still displays. This confused and unsettled new users.

**Comment by redmatrix** [comment]
I just changed the profile photo on a test account and the visible change (on my site) was instantaneous despite the cache warning. It was also updated on a different connected site within two minutes. So it may be browser dependent. I'm using FF on windows at the moment. 

In the right-hand corner, upon profile photo submission you'll see 

**Shift-reload the page or clear browser cache 
if the new photo does not display immediately.**

And we change the timestamp parameter on the large profile photo displaying on the return page so that it is not cached and should be displayed immediately (removing cache interval leads to complaints by sysadmins). We had a 0 cache time on all photos at one time so that any changes in content or permissions would be reflected instantaneously. Admins were angry and we lost a few good folks over the fracas. We now compromise and provide a one day cache so that the browser isn't hitting the server for every image repeatedly - even one's that it saw 30 seconds ago. And we add a timestamp parameter to the "large" profile photos on profile and channel pages so that they are not cached. 

This one day cache is configurable. If you have an issue, configure it. 

       // The photo cache default is 1 day to provide a privacy trade-off,
        // as somebody reducing photo permissions on a photo that is already
        // "in the wild" won't be able to stop the photo from being viewed
        // for this amount amount of time once it is in the browser cache.
        // The privacy expectations of your site members and their perception
        // of privacy where it affects the entire project may be affected.
        // This has performance considerations but we highly recommend you
        // leave it alone.



A somewhat related issue is that it can take up to a day for your new profile photo to make the rounds to the hubs of all your connections.

**Comment by kenrestivo** [comment]
I watched a few people have the problem, and shift-reload didn't help. Regrettably I didn't take note of their browser/OS combinations, but it was probably Safari on OSX.

It sounds like this is a much more complex issue than I'd have expected. I can't offer too much suggestion other than perhaps making the profile photo filename an md5 of the file contents, not of the user's channel, and updating that pointer when the photo changes, and then letting the admin's and ISP's usual cache infrastructure do its job without mucking with it. That may or may not be possible; apologies for not understanding the implementation at the moment.

**Comment by kenrestivo** [comment]
I'm going to close this and wait to possibly reopen it if/when t can be duplicated.
