### ISSUE TITLE
Observer tags don't work

### ISSUE THREAD

**Issue by zzottel** [redmatrix/hubzilla#17]
Just found that I'm always presented with the observer=0 option in Hubzilla.

Reason seems to be that prepare_text() (and thus bbcode()) is called with $cache=true in prepare_body().

Might fix that myself if you tell me how that's supposed to work.

**Comment by redmatrix** [comment]
Ah, my bad. I started generating an html cache in the db so we only had to parse the majority of bbcode once, and then a quick run at display time to another function (bbcode_runtime() or bbcode_observer() or something like that to parse just the observer stuff when a stream was being rendered. The problem is there are a lot of tag callbacks which use the observer in subtle ways by calling zid() and this had some undesirable side effects so I undid this bbcode caching until I go through and find all of them, but forgot to turn off the cache flag when I undid it. So yes - [$cache = false] should fix it for now.

**Comment by zzottel** [comment]
Pull requested. Can't merge myself—unless this is (currently?) intended, please give me write access to the repo.

**Comment by redmatrix** [comment]
At the moment I don't have the optimal setup to merge from redmatrix without conflict so I want to make sure I check everything going in for dependencies in the other project. There are a lot of merge conflicts currently that require looking over everything carefully.  I'll give you repo write access as soon as I figure the best way to cross-merge between the two.

**Comment by zzottel** [comment]
Ok, no need to hurry. Just wanted to mention it in case it was non-intentional.
