### ISSUE TITLE
remove or block hubzilla_er directory from production websites

### ISSUE THREAD

**Issue by redmatrix** [redmatrix/hubzilla#175]
hubzilla_er is an auto-generated directory from SchemaSpy. It creates HTML pages for inspecting database schema relationships. We do not want this on productions sites - only dev sites. This should be removed from the repository ideally and generated on demand only, by those interested in the data; much as we do with doxygen.

**Comment by kenrestivo** [comment]
I created a skeleton Makefile in https://github.com/redmatrix/hubzilla/blob/master/hubzilla_er/Makefile . It needs help. It's been years since I messed around with Makefiles and my make-fu has gone. Once the makefile works properly or is replaced by a non-make script, the content can be deleted from the directory and the schemaspy can be as easy to generate (just type make) as the documentation.

**Comment by redmatrix** [comment]
Oops. I removed the directory before seeing that you actually had a note about it here. I've brought back just the Makefile under util/hubzilla_er/Makefile

If you wish to preserve all the generated files, checkout 38d5131 and copy hubzilla_er somewhere safe before checking out master again.

**Comment by kenrestivo** [comment]
Cool, the Makefile is all that was needed. Thanks for this.
