### ISSUE TITLE
Nice, friendly-looking error page instead of WSOD?

### ISSUE THREAD

**Issue by kenrestivo** [redmatrix/hubzilla#181]
Would someone like to design a nice, friendly-looking error page to display in cases where the database has gone out or is unavailable? 

Right now it throws an HTTP error and displays a terse message.

If someone has some design skills and wants to come up with a nicer page (that doesn't depend on the database being available) then it'd be easy to display it.

**Comment by royalterra** [comment]
I not agree with that folks attacking your server will know when your mysql sever is down for true . And for users  is very bad impression look a mysql error in your front page . We can simple add a php script send a mail to the admin if mysql is down every time is execute the cron

<?php
	@mysql_connect("remotehost", "foo", "bar"); //try a connection
	switch(mysql_errno())
	{
		case 0: //just in case we accidentally get a valid connection
			mysql_close(); //we don't break here because we want to fall through to "server running"
		case 1045: //server responded with access denied
			echo "MySQL server running";
			break;
		case 2003: //no MySQL server responded
			echo "MySQL server not running";
			break;
		case 2005: //oops! can't find the server
			echo "Cannot find server - check host name";
			break;
		default: //sanity check in case I missed something above; these responses should probably be logged for later review
			echo "Unknown response: ".mysql_errno().": ".mysql_error();
	}
?>

**Comment by royalterra** [comment]
or you can more easy install in your server MONIT that will send you a email every time a service stop in your server https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-monit

**Comment by royalterra** [comment]
I think some of the problems here is we need to setup a minimum requirements for install Hubzilla . That means not only have SSL also Ram Memory of the server and MYSQL memory very possible your server crash down because a memory problem . Hubzilla is OK in a small VPS with 3 or 4 users but if this going up You need more resources 
[0.14] [0.15] [0.17] -  	1.8%us, 0.4%sy, - 0.0%wa	- 18.3% [1536292 kB]	
That is a example of one Installation with more 10 channels and users
Memory ram is 18.3% of 8 GB for the HUB and Mysql Ram I use is 8% 

Again some of the problems I not think is related to Hubzilla itself is more a question of have the right server and have the right server manager configuration

That figures I post here can't be exact but are working around that

**Comment by kenrestivo** [comment]
That code was cut and pasted from a sitepoint post in 2007 http://www.sitepoint.com/community/t/php-script-to-check-mysql-status/3422

If you want to contribute a plugin to notify admins of errors, that might be helpful. I use Monit but others might like to have that baked into Hubzilla.

Trying to get back on focus again: the sad fact of the internet is that servers go down. When they do, something has to be displayed to the user. To avoid getting derailed, I'll refocus on this issue: would someone like to help by contributing a friendly error page. @mike mentioned that there was one already in the repo before, but it got removed years ago; maybe it could be resurrected.

**Comment by royalterra** [comment]
Kerestivo I am really tired of you the problem of MYsql is because your server can hold a few mysql request you are the only with that problems but of course you no post the Values of your server. No Worry from now on   I will reply to my only questions I open and I will not open any more questions here . Really I like to participate in a project with open mind people not people like you when to take the project to your only Ideas. 
Really I believe you have very poor performance with setup servers  and dealing with protocols possible you have some nice skills in PHP or any other language but I already see some of your other skills and  you normally when to take out a idea when your knowledge no go more far away. 
In time you are here I am off from Hubzilla GITHUB have a nice day.

**Comment by mike** [comment]
i'm mike btw :sweat_smile:

**Comment by kenrestivo** [comment]
Fixed by the *other* Mike, in 301072a86cacd2620a08cf07f2cef55dffac3c2f
