### ISSUE TITLE
When playing an audio file, clicking the LIKE button causes the player to disappear

### ISSUE THREAD

**Issue by kenrestivo** [redmatrix/hubzilla#185]
Playing an embedded HTML5 audio file, if you like it and click the like button while it is playing, the player disappears and shows "[embedded content, reload page]" instead.

**Comment by redmatrix** [comment]
This is because browsers tend to pre-fetch some media elements. The situation may have improved in the last couple of years, but in the early days of html5 the entire file was fetched - every time somebody liked or commented on the post causing us to re-render the post (and re-fetch the complete media file). I was at the time on a more limited internet plan than I am now and one popular video caused me to use my entire allocated monthly bandwidth because it got a fair number of likes and comments. 

Also while this content is being fetched your page is unresponsive - possibly for several minutes and the dreaded "script on this page stopped responding" message often pops up. 

Oembed with scribd is equally problematic. They have no problem embedding a 200M ebook; with the same results as the audio/video.  Your browser is frozen, your internet usage exceeds quota and can cost you hundreds of dollars out of pocket.

In this case it's the same issue but different symptoms - again it's the content reload and re-render that is source of the problem. A potential solution for the precise scenario in this bug is to query the browser somehow to determine if a media element is in this thread or on this page and it is active (playing). We could then block reloads of either this item or the entire page until it is no longer active.  And while it's possible this could be accomplished for the built-in media elements the same solution probably wouldn't work for youtube (player), vimeo, soundcloud, etc. because each player would have different ways of figuring out if it is currently active (if indeed there is any way to determine this on brand 'x' media player for any value of 'x'). 

And in the sake of completeness, one could also rewrite the content updaters to see if the text body of the message itself changed (or just the like count, etc.) and only update the elements which have changed.

**Comment by kenrestivo** [comment]
Thanks. That commit basically stops the like from happening at all (pinwheel, but no action). If you hit like when the media player is not playing, it shows the [embedded content].

It's a minor issue (might be useful to have tags for severity in the issue tracker too).

Maybe someone who has more UI and javascript-fu would want to tackle it. I'll ping dbene to see if he's interested.

**Comment by redmatrix** [comment]
The like still happens and is recorded. It just doesn't display until after you're done with the media (plus the remainder of the remaining normal "ping" time). Then everything returns to normal again. To get rid of the [embedded content] thing we need a preference for those who live in countries or regions with metered internet traffic, like mine. It's not technically hard, I'm just trying to be nice to peoples' pocket books. It's pretty nasty getting a bill for $500 for excess internet usage and trying to explain to the wife it was because one of your friends uploaded an ebook and a number of other people liked it.

**Comment by kenrestivo** [comment]
I think this problem was solved in 1b30210 . If audio files no longer pre-load, is there any reason for the [embedded content] thing anymore?

**Comment by redmatrix** [comment]
There are several ways of embedding things. The built-in player was never the largest of my worries. It was just one of several things that could suck in large files repeatedly without your direct involvement.

I'll pull out the substitution, but I'll probably put it back in the future as a feature or option targetted specifically at oembed; which is due for a refactor anyway.
