### ISSUE TITLE
Forum channels not listed as forums when using custom/expert permissions

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#186]
When you set a public forum to the permission category 'Custom/Expert Mode' and then set 'Can forward to all my channel contacts via post @mentions' to (e.g.) 'Approved connections', the channel is **not** listed as a forum in the directory. It seems it is only listed as a forum when using the public community forum preset. 

One casus is the channel anarchism@hubzilla.nl. Because the connection list is visible to everybody, I had to change that permission to only approved connections because of privacy concerns. That can only be done by using the Custom/Expert Mode. But now it is not listed as a forum.

**Comment by redmatrix** [comment]
It can be very difficult to determine a *public* forum when custom permissions are in place. Here's what we check:

include/zot.php:3677

        if(($t) && (($t[0]['abook_my_perms'] & PERMS_W_TAGWALL) && (! ($t[0]['abook_my_perms'] & PERMS_W_STREAM))))
            $public_forum = true;

**Comment by jeroenpraat** [comment]
OK, let's go back to the Anarchism channel:
- abook_my_perms = 218363
- channel_w_tagwall = 8
- channel_w_stream = 8

What goes wrong here?

**Comment by jeroenpraat** [comment]
As a comparison: when I check the Animate GIF Channel (that's set to the public forum preset and therefore is listed as forum in the directory):
- abook_my_terms = 218623
- channel_w_tagwall = 8
- channel_w_stream = 8

**Comment by kenrestivo** [comment]
I've seen this behavior too and wondered about it. Thanks for shedding some light on it.

So the code @redmatrix pointed to is here: https://github.com/redmatrix/hubzilla/blob/master/include/zot.php#L3677

The perms defined here:
https://github.com/redmatrix/hubzilla/blob/master/boot.php#L285

It's a bitmask, which is familiar to kernel, unix systems, and embedded programmers, but not always to web programmers or designers.

That number 218623 when considered unsigned and translated to binary means that indeed W_TAGWALL and W_STREAM are set.

But that check in zot.php, if I'm reading it right, seems to consider a forum public if W_STREAM is *not* set.

I guess, translating to English, maybe turning off W_STREAM (whatever that is in the checkboxes) might make zot.php consider it public.

I don't know if resolving it means changing code or documenting the behavior.

**Comment by redmatrix** [comment]
Correct. The check that perms_w_stream is *not* set is because for custom permissions we don't really know if it's a normal channel that just allows tagwall permissions. if perms_w_stream is false, it means that the channel isn't really interested in viewing stream content. Most "social profiles" of some form interact mostly from the stream (network or grid) page. Forums never touch that page. The only thing that's important to a forum is the channel wall. The stream (network or grid) page is just noise that nobody ever looks at. 

We have *lots* of custom social profiles that enable tagwall permissions. They are not public forums nor should they be listed as public forums. There are people with some pretty outrageous settings.  

This was the only sane way of distinguishing the two. Using the predefined permissions roles everything just works. If you use custom permissions, things can behave much differently than the predefined roles. It's called "custom/expert" mode for a reason. You're choosing a set of permissions which doesn't match any standard behaviour. It's OK to do this, but the pubforum check is one place where we try and see if the channel exhibits a known standard behaviour - that of a public forum. In fact there is no such thing as a public forum at the core of zot. Relationships and channel types are merely a set of permissions. The abstractions were put in place because people demanded them. They want everything to fit into nice little categories. We allow you to do that. We also allow you to make up entirely new permissions and channel types that we haven't dreamed of.

**Comment by jeroenpraat** [comment]
Sorry, but I try to understand where W_TAGWALL and W_STREAM are set in the channel settings. When I look into https://github.com/redmatrix/hubzilla/blob/master/permissions.php#L638 W_TAGWALL and W_STREAM are mentioned a few times:

````php
$ret['perms_follow'] = PERMS_R_STREAM|PERMS_R_PROFILE|PERMS_R_ABOOK|PERMS_W_STREAM|PERMS_W_WALL|PERMS_W_COMMENT|PERMS_W_MAIL|PERMS_W_CHAT|PERMS_R_STORAGE|PERMS_R_PAGES|PERMS_A_REPUBLISH|PERMS_W_LIKE|PERMS_W_TAGWALL;
 $ret['perms_accept'] = PERMS_R_STREAM|PERMS_R_PROFILE|PERMS_R_ABOOK|PERMS_W_STREAM|PERMS_W_WALL|PERMS_W_COMMENT|PERMS_W_MAIL|PERMS_W_CHAT|PERMS_R_STORAGE|PERMS_R_PAGES|PERMS_A_REPUBLISH|PERMS_W_LIKE|PERMS_W_TAGWALL;

$ret['channel_w_stream']    = PERMS_SPECIFIC;
$ret['channel_w_wall']      = PERMS_SPECIFIC;
````

I totally understand what you are saying @redmatrix, but why doesn't a channel show up as a forum when public forum is changed to custom mode, without modifications in the advanced permissions. Cause when I look in that it looks like it keeps the above settings, but the channel looses its forum directory flag.

**Comment by jeroenpraat** [comment]
One more thing: When I set 'Can send me their channel stream and posts' (W_STREAM ?) to 'Nobody, except my self' + 'Can forward to all my channel contacts via post @mentions' (W_TAGWALL?) to 'Approved connections' zot.php should accept it as a forum, right? But it does not.

**Comment by kenrestivo** [comment]
This explanation is great and should be copied/pasted into the docs somewhere.
With the addition of one more thing: it'd be very useful to have a mapping somewhere between the perms in boot.php and the corresponding checkboxes in the UI. Then someone choosing to do "expert" mode with the checkboxes would not be flying blind.

**Comment by redmatrix** [comment]
@jeroenpraat You're on the right track but the wrong form. 

Settings => Connection Default Permissions

**Comment by jeroenpraat** [comment]
Great, that works. But you have to set that one in the advanced permissions first to PERMS_SPECIFIC. So that sounds not very logical to me. Is there a reason for that? Why not using the advanced permissions?

**Comment by redmatrix** [comment]
That was chosen because public forums are generally "auto-accept" (if you need permissions to join they aren't public), so if you've got a custom permission role we look at what permissions you hand out when you accept a connection and see if they look remotely like the settings of a public forum. I spent hours getting this sorted for those with "expert" permissions. I tried a number of things over a period of several days and this is the best I could do. If you can come up with something better that doesn't give lots of false positives - go for it.

**Comment by jeroenpraat** [comment]
OK, than is the best we can do to document it. Will do that later today.

**Comment by jeroenpraat** [comment]
There seems to be regression here.  Since 1.12 forums with custom permissions are not listed anymore in the forum widget. The permissions were not changed for those forums.

**Comment by zotlabs** [comment]
You're welcome to have a look. 

include/zot.php:L3788

**Comment by jeroenpraat** [comment]
Thanks, although somehow it magically solved itself. I see your fix is in dev, and hubzilla.nl is on master, but still I now see those forums listed.
