### ISSUE TITLE
Apache using 100% CPU, locking up, etc

### ISSUE THREAD

**Issue by kenrestivo** [redmatrix/hubzilla#188]
Just leaving this here as a catch-all. I'd be happy to attempt to gather more data on this. I'm seeing Apache becoming unresponsive, and MySQL crashing, under normal, very light usage on a 2GB RAM VPS. I understand that the stated design goal for Hubzilla is that it could be run on simple, cheap shared hosting. It is failing regularly on a Xen virtualized VPS.

With a 1.0 release near, I'd suggest at least attempting to address these kinds of reliability/performance problems. They might be easy to fix, or they might be symptoms of a design/architecture flaw that can't be fixed without a major rewrite, or they might reqre changing the install requirements to require a more high-powered server/VPS, more RAM, more CPU cores, etc. which can be documented (or even automatically checked at install time) before release.

Related: https://github.com/redmatrix/hubzilla/issues/178

@habeascodice 's comment there seems like it should get much more attention:
> The poller reads outq while the importer is trying to write it, that causes a race condition which causes everything to block on each other, hence the OOM. Similar situation for the directory updates.

**Comment by kenrestivo** [comment]
As of this moment:
```sh
$ ps -auxww |grep /usr/bin/php |wc -l
66
```
A couple weeks worth of monit history here:
https://hub.spaz.org/cloud/bamfic/logs/errors.log

**Comment by zzottel** [comment]
In my experience, Apache processes seem to start hogging CPU if a PHP process that was started by Apache can't get database access for whatever reason. Instead of terminating correctly, the Apache process will continue eating as much CPU as it can until Apache is restarted.

In my case, this kind of scenario happened rather frequently for a while because
- I have three RedMatrix servers and one Hubzilla server on the same hub. Very few users, but as there are clones, when a lot of stuff comes in (especially when my whole server has been down for a while), the four hubs not only have to manage the incoming stream of data, but also deliver a lot among each other, so things can get really busy.
- In Debian default settings, in mpm_prefork.conf for Apache, the MaxRequestWorkers setting is set to 150 (150 Apache processes running simultaneously), but in my.cnf for MySQL, the max_connections setting is set to 100.

So under high RedMatrix/Hubzilla network load, 150 Apache processes would try to access a maximum of 100 simultaneous MySQL connections, so many of them wouldn't get a database connection, and thus Apache processes would start to run wild.

Since I set MySQL max_connections to 200, I never had that problem again.

**Comment by jeroenpraat** [comment]
I overlooked this issue, but I solved the Apache problem a while ago with set added to <IfModule mpm_prefork_module> in /etc/apache2/mods-enabled/mpm_prefork.conf:

GracefulShutdownTimeout  300

It fixed the Apache processes just hanging in there for eternity.

**Comment by kenrestivo** [comment]
This is fantastic. Does one of you feel like adding these two instructions to https://github.com/redmatrix/hubzilla/blob/master/install/INSTALL.txt , and/or adding these to .htaccess . If not, I can do it.

**Comment by zzottel** [comment]
Added the info to INSTALL.txt (pull request pending).

**Comment by git-marijus** [comment]
I will close this issue now. Please reopen if you still have issues.

**Comment by royalterra** [comment]
@kenrestivo I start with similar problems but no mysql because the mysql server is holding . But make a simple test work for me and the CPU coming to minimum in my server with apache 2.4.14 in 
.htaccess change 
 Options -Indexes   for this line AllowOverride Options=-Indexes
if you do reboot better for kill absolutely any process including any new cron call you no like that 
stop cron stop mysql stop apache kill any php process can be hold . Start everything again 

I change like that and now are 6 hours I not get any problem at all including CPU is very low simple test and tell me Thanks

**Comment by kenrestivo** [comment]
Reopening. Apache is still using 100% CPU persistently even after tuning MySQL settings as recommended. Still not sure why, unfortunately.

**Comment by kenrestivo** [comment]
FWIW:
mods-enabled/mpm_pref*
```apache
<IfModule mpm_prefork_module>
        StartServers                     5
        MinSpareServers           5
        MaxSpareServers          10
        MaxRequestWorkers         150
        MaxConnectionsPerChild   0
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
# Conflicts: mpm_event mpm_worker mpm_itk
LoadModule mpm_prefork_module /usr/lib/apache2/modules/mod_mpm_prefork.so
```

And my.cnf:
```conf
max_connections        = 300
```

**Comment by royalterra** [comment]
@kenrestivo I really check every thing and follow to absurd ideas my self to be ridiculous . My configuration is similar but with different values more high because my server ram etc . Anyway No one reply to us no one reply why/usr/bin/php include/queue.php open several times and not close and start eating your ram and d in your case crash your mysql etc etc . Why channels are not delete from database ? UHH Surprise that is order . Really @HaakonME @redmatrix any one can please reply to Mr @kenrestivo and to me and say what going on.

**Comment by royalterra** [comment]
And if is got for you 
<IfModule mpm_prefork_module>
StartServers 6
MinSpareServers 5
MaxSpareServers 15
        MaxRequestWorkers        250
MaxRequestsPerChild 4000
        MaxConnectionsPerChild   3000
###GracefulShutdownTimeout 300
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

You not need to add LoadModule mpm_prefork_module /usr/lib/apache2/modules/mod_mpm_prefork.so

because is already loaded if you no install from sources

**Comment by kenrestivo** [comment]
Well it has been stable for the past week so I guess whatever was wrong is not presenting itself right now.

Closing this until 1) it shows up again and 2) there's some kind of helpful debug error message that I or someone else can locate.
