### ISSUE TITLE
ZOT Problems Holding Process Broken Apache2 

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#199]
Look every time a process is Hol  d 26698	www-data	385.70 MB	/usr/bin/php include/externals.php   28652	www-data	385.70 MB	/usr/bin/php include/externals.php

Coming to all this  Illegal string offset 'hash' and after some Apache will have few several holding process of 400 megas or more . My Mysql no broke down I make resources for that but this problem is not relate a single installation I already test with 3 more separate domains and is the seam

PHP Warning:  Illegal string offset 'hash' in /var/www/server/include/zot.php on line 1249
PHP Stack trace:
PHP   1. {main}() /var/www/server/include/deliver.php:0
PHP   2. deliver_run() /var/www/server/include/deliver.php:176
PHP   3. zot_import() /var/www/server/include/deliver.php:128
PHP Warning:  Illegal string offset 'hash' in /var/www/server/include/zot.php on line 1250
PHP Stack trace:
PHP   1. {main}() /var/www/server/include/deliver.php:0
PHP   2. deliver_run() /var/www/server/include/deliver.php:176
PHP   3. zot_import() /var/www/server/include/deliver.php:128

**Comment by royalterra** [comment]
Looking more in the possible problems I discover in all installations
util/config system directory_realm
Show Up Nothing That is in new installations and old installations 
I change for util/config system directory_realm RED_GLOBAL and all look to communicate by now after 2 hours

**Comment by redmatrix** [comment]
Best to keep one issue per issue report. 

If there is no directory realm, it always defaults to 'RED_GLOBAL' (actually the value returned by the constant DIRECTORY_REALM). 

It should not ever need to be set in normal operation unless you redefined the DIRECTORY_REALM constant to something weird. 

The string offset error has never been reported by anybody else and looking through the code it is difficult to fathom how it could happen. As mentioned in an earlier report you made about this error, one needs to log the value of the malformed recipients array element at that point so we can see what's in it, and then determine how the errant string/whatever got there and figure out why it isn't an array. 

The memory usage in include/expire is most likely due to old redmatrix sites which have no limiting code, and are trying to return all public posts since the beginning of time. We randomise these queries so that if this ever happens or some site starts streaming feature movies as a zot feed it won't prevent content from being imported; even though the import process for that particular site might get overwhelmed and get killed for consuming too much memory.  You might wish to note in the application log what URL was being accessed during that time and add the site to your blacklist.

**Comment by royalterra** [comment]
Ok @redmatrix The 2 working domains I have are setup define ( 'DIRECTORY_REALM',            'RED_GLOBAL'); I will watch now and see

**Comment by royalterra** [comment]
@redmatrix here is a strain log take from the cron /usr/bin/php include/poller.php before start crash 
libpng warning: Ignoring incorrect cHRM value when sRGB is also present
wx=0.280560, wy=0.295820, rx=0.639090, ry=0.339920
gx=0.318310, gy=0.641930, bx=0.124060, by=0.043880

**Comment by royalterra** [comment]
@redmatrix No worry I l already solve now all the problems at the end . The previous messages from @git-marijus make think if I need to share what I know or not but one arrogance person no go to damage the rest and I will post the solution when I have time

**Comment by git-marijus** [comment]
@royalterra i am really beeing far from arrogant...
i just think what you posted in issue #206 is not related to issue #206

**Comment by royalterra** [comment]
Ok @git-marijus Is Ok fine . We forget this and go on . Thanks
