### ISSUE TITLE
South American Spanish and Spanish ES and Hebrew Translations

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#234]
I really comment with my users from SPAIN speaking Spanish ES and is really confuse all that. 
Spanish ES is different from the People Speak Spanish in South America . Works and common sentences are express in different terms. 
Us Spanish Speaker born in Spain I agree with my users terms like Ajustes de la característica o el complemento related to Feature/Addon settings That not make sense "addon = extension"  in software use in Spain you will translate
"Ajustes de Extensiones" is totalmente diferente a "Ajustes de la característica o el complemento" is a translation no make sense for Spanish Speakers from Spain. 
Many Public software and webs like google yahoo etc  have 2 variants Spanish ES and Spanish South America but here is all in one.
For that I think we need to duplicate the the translation there already and make the opportune changes for Spanish ES

Seam confusion I not have idea why there 2 branches of Hebrew . To my Knowledge there only Modern Hebrew and Biblical Hebrew . In Israel people speak Modern Hebrew and if your are in the synagogue you can speak Biblical Hebrew for read the Torah . Why there 2 branches of Hebrew?

**Comment by royalterra** [comment]
After I talk with Manuel and hi deny what is logical In Twitter , Facebook, and other Networks Spanish have different dialects in latino America and by example Facebook include 4 variants of Spanish . That means and I have probe and evidence I am right with only look in other social networks. You not need to be Einstein for see that.

Now Manuel have his ego and also personal reasons hi express clear in a email but hi not explain what is clear in Facebook, Twitter, Yahoo, Google and so on about the variants of Spanish .

Now is Hubzilla go that Line possible will be a god idea a Option in the Admin Section for Use a own translation . by EXample Language Spanish Option 1 Translations include in Hubzilla Option 2 Translation make for the Admin keep in a separate folder for not conflict with git pull

**Comment by redmatrix** [comment]
We provide variants already for English: en, en-gb, and en-au. The en-gb hstrings.php file includes the en file and then just over-rides the strings that are different. 

This cannot be done in transifex and requires a bit of code ability. And we still do our best to provide a "neutral" translation in the base file that can be understood by any speaker of any regional dialect. This takes some work and coordination with folks speaking different dialects but keeps the differences to a minimum.

**Comment by royalterra** [comment]
Ok @redmatrix many of the translatiosn not make Sense a link normally is a reference tittle not a description that is the seam in any software or big social network in Spain . I not see before all this  because my browser is always in English but some translations not have the seam meaning if you translate back. How is that possible ? 
I not say all is incorrect but from the moment Look more a Latino Translations not have sense for Spanish or any person in any country study or Learn Spanish . Spanish language are regulate by the Royal Spanish Academy. Not for a Latino Dialect of Spanish.  Really I will be more happy if the admin of the translations are 2 one with Latino Origin there already and 1 Native Born Spanish Speaker. Possible that will solve any issues and make more equal for every one

**Comment by redmatrix** [comment]
My browser (firefox recognises 18 Spanish variants. It sounds like you want your variant to be es-es (Spanish - Spain). So create es-es and include the file from es/hstrings.php and then change the (hopefully) small number of strings that are different. 

English came originally from Britain, but the default English translation is US - because more people speak that variant than speak the British variant. 

Unfortunately, more people speak Latin American Spanish than speak Spain Spanish. So you can argue all day about what flavour is represented by 'es' but I suggest it should probably be the most widely used composite - therefore 'es' should be what you call Latino Spanish - it is recognised by more people in the world than textbook Academy Spanish. This saves us from having 17 variants of Spanish for the rest of the world (and 17 different translation files that need to be maintained by people) and one for Spain. This is precisely what we've done for English. Britain should be the definitive dialect for 'en' but it is not, because en-us is much more widely used than British English.

If you disagree with this choice please work it out with all the other Spanish speakers in the project.

**Comment by royalterra** [comment]
@redmatrix I am not talking about a variants like English British and ENglish USA . Spanish is a little more complicate . Take a look in FB I choice change to SPAnisH you will see 5 variants to 5 country's.
Why ? Because people is Spain use expressions different to the Spanish . By example in Spain they say coche for means "car" and in south America in some parts they say "carro" And I can think you have a horse trailer what means really different . Easy to check reference  http://www.spanishdict.com/translate/carro

What I try to explain to you is we not have the seam expressions and we make in Spanish very different descriptions for describe anything 
I think this web explain to you what I am talking about 
http://blog.esl-languages.com/blog/destinations-worldwide/latin-america/differences-latin-american-spanish-spanish-spain/

Now you like to continue after read that with that translation . Ok tell me how to overwrite and not broken nothing and I will use my own translation

**Comment by royalterra** [comment]
And redmatrix the flag es is for Spanish - Spain and is a  international standard . No matter how many people is in a place

**Comment by redmatrix** [comment]
> If you disagree with this choice please work it out with all the other Spanish speakers in the project.

**Comment by royalterra** [comment]
redmatrix when I try to speak with the admin of the project I have ben insult us troll and anti-muslim 
Sorry I have Honor . I can talk with bad educated and intolerant people are doing the translation. I will go my own and see how to overwrite the Spanish translation in my server.

**Comment by royalterra** [comment]
THE BEAUTIFUL MESSAGE HI SEND TO ME NOW . I hope you no lose the translation in Google Translate 
Manuel Jiménez Friaza
about 12 hours ago
Ya te respondí. Pero te ruego que no lo hagas tú: empiezo hoy mis vacaciones de Navidad, estoy cansado y lo último que deseo es polemizar contigo.

No me gusta tu presunción de saber de todo ni tu castellano lleno de incorrecciones, faltas de ortografía y vulgarismos, ni tus fotografías con su carga de machismo o islamofobia. Tampoco entiendo tu pasión de converso por esta red que, en tan poco tiempo, ya pretendes conocer mejor que muchos veteranos desarrolladores, ni tu afán por captar gente para tus múltiples servidores. A veces creo que te comportas como un "troll".

No te digo todo esto para ofenderte ni zaherirte, ni mucho menos, no te conozco (igual en persona, delante de un caafé, podríamos incluso llegar a ser amigos, pero no es el caso), solo te interpreto por tus palabras. Solo quiero que entiendas por qué voy a desconectar de ti definitivamente en estos días y para que no te quedes con la sensación de que soy un soberbio, como decías en mi canal "Poetas", pensando seguramente que era de otro.

**Comment by royalterra** [comment]
Now I not waste more my time is late and I go to Sleep. But you know in

**Comment by redmatrix** [comment]
Funny you mention Facebook. If you choose "Spanish" in Facebook you get es_LA (which is their own variant of Latin American Spanish - it is not a valid ISO code as Spanish isn't an official language in Laos). So at least to Facebook "Spanish" means Latin American Spanish by default, *not* as spoken in Spain. 

If you want Spanish as spoken in Spain, you use "Spanish (Spain)" which is es_ES. They also provide es_MX (Mexico) and es_VE (Venezuela) and es_CO (Colombia) and es_CL (Chile). There is no plain 'es' selection - probably because they got tired of people arguing about it. I suggest we do the same and remove 'es' completely and force people to choose a national or regional dialect. This means if somebody has their browser set to 'es' as the only preferred language, we would not recognise it, and instead default to English.

**Comment by jeroenpraat** [comment]
So to summaries it Mike: we move es to es_ES and if other Spanish variants want to have their own translation (like es_MX) they can go ahead. Like pt_PT and pt_BR. I can live with that. 

I can arrange that this afternoon or evening in our code, but not in Transifex. You Mike can give me admin permission on Transifex if you want, so I can make the needed changes.

**Comment by royalterra** [comment]
The problem @jeroenpraat the people are making the translation now es or es_ES a using common sentences in Latino America  or what I suspect in some translations some one just take google translate and yeah go on . The people make this translation I suspect are form Latino America ok is easy Job we can make any iso code start by 'es' and is not 'es-es' is send to es-la is not a easy code like say @redmatrix with that you have 2 variants one es-es Spain and one es-la for Latino America .

The solution is easy : 
1.- clone the actual Spanish
2.- make one es-es and other es-la 
Anyone browser start with es and is not es-es automatic get es-la translation with that People in Latino America can resolve the own differences and we can solve the own difference in Spanish Spain

The possible issue here no understand for people speak English is some works or expression are totally difference from Spain Mainland and Latino America. Some place still they  talk Spanish with expressions not issue in modern Spanish (Spain) but they are correct in times of Columbus .
Some Verbs  like "coger" means "to take" in English can means a rude work in Latino America and like that so on and so on . We can write a book and we not finish never.

All we Speak Spanish but we have serious differences and for that Microsoft release a different version for Latino America , Mobiles Company's include difference translations and Ubuntu , Mint, Debian, Centos, redhat etc all have include a Spanish for Spain and one or few different versions for Latino America

**Comment by jeroenpraat** [comment]
As you probably know Hubzilla uses the browser's content language to decide which language to display. For languages spoken in more than country, a locale is added, like ES, resulting in es-ES. As @redmatrix  said LA from es-LA is not a valid locale for Spanish (LA is from Laos). So es-LA is not going to work for Hubzilla. At least in Firefox, that follows the official ISO standards. In Chrome/Chromium you can select Latin American Spanish, but the code (es-419) is not official. See https://en.wikipedia.org/wiki/Language_code#Common_schemes. 

So I can do the following: 
- copy view/es to view/es-419 and see if this works in Firefox. If not, we can maybe use symlinks from (e.g.) es-419 to es-MX, es-AR, etc.
- Let me also wait for @redmatrix if he wants me to give me maintainer access to the Redmatrix team in Transifex, so I can make to appropriate changes over there.

**Comment by royalterra** [comment]
OK we can do more easy : 
1.- Spanish Spain es-ES Go to one Translation 
2.- Any codes Ending in all That below here go to one Latino translation and now we have two separate translations. . I believe people from Latino America can agree easy to the own translation and Spanish Mainland es-ES go with the Modern Spanish following the rules of the Royal Spanish Academy
 
es-AR	Spanish (Argentina)
es-BO	Spanish (Bolivia)
es-CL	Spanish (Chile)
es-CO	Spanish (Colombia)
es-CR	Spanish (Costa Rica)
es-DO	Spanish (Dominican Republic)
es-EC	Spanish (Ecuador)
es-GT	Spanish (Guatemala)
es-HN	Spanish (Honduras)
es-MX	Spanish (Mexico)
es-NI	Spanish (Nicaragua)
es-PA	Spanish (Panama)
es-PE	Spanish (Peru)
es-PR	Spanish (Puerto Rico)
es-PY	Spanish (Paraguay)
es-SV	Spanish (El Salvador)
es-UY	Spanish (Uruguay)
es-VE	Spanish (Venezuela)

**Comment by jeroenpraat** [comment]
After some investigation: We can't (currently) use es-419 in Hubzilla, because we use [intl](https://github.com/redmatrix/hubzilla/tree/master/library/intl). See also [the list of Spanish variants](https://github.com/redmatrix/hubzilla/tree/master/library/intl/resources/language) possible.

So the only option I see now is:
- In Transifex we copy es to es-419 (yes in Transifex es-419 is available). Spanish speakers from Latin-America can try to modify the es-419 language to whatever they prefer. 
- On Hubzilla and Transifex we move es to es-es.
- On Hubzilla we create es-419, and make symlinks from e.g. es-mx, es-ar, es-co, etc to es-419. 
- If in the future someone from e.g. Argentina want to create their own es-ar translation they can request that on Transifex and on Hubzilla the view/es-ar symlink can be replaced by a real view/es-ar directory. 

@redmatrix Are you able and willing to give me the necessary permissions on Transifex?

**Comment by jeroenpraat** [comment]
@royalterra I think we agree.

**Comment by royalterra** [comment]
@jeroenpraat   Yes that is fine for me I think like that every one will be happy

**Comment by jeroenpraat** [comment]
*one remark: view/es-419 goes to view/.es-419. Or else it shows up in the language selector on /lang. Still the symlinks will work.

**Comment by jeroenpraat** [comment]
See latest commit

**Comment by jeroenpraat** [comment]
And about Hebrew: Yes I agree, Hebrew is only spoken in Israel, so no need to have he-IL.

**Comment by royalterra** [comment]
yes I start in Transifex with hebrew Israel alone with some work some one left after I observe there and other hebrew translation with and other user stop work 4 months ago. I send a email to him for join me in Hebrew Israel and try to make soon the target of 50% . Possible I can join part of the other work together but I need to see both with Attention I will start this Night with that

**Comment by jeroenpraat** [comment]
I mean the opposite. Only create a Hebrew translation (he) and NOT a Hebrew Israel (he-il) translation. he=he-il

**Comment by royalterra** [comment]
Hi send me a email an say there some problems:
Content of the email:
I have opened Hebrew (Israel) (he_IL) because I was not able to upload an update to Hebrew (he).
The translation I focus on is Hebrew (he).
https://www.transifex.com/Friendica/teams/14920/he/

**Comment by jeroenpraat** [comment]
I'm going to revert what I did. It makes the language selector to long, but especially because I made a feature request upstream: https://github.com/commerceguys/intl/issues/26.

I'm going to remove all the symlinks and make a symlink from es to .es-419. So all Spanish speakers outside Spain will receive the .es-419 one. Later when upstream is ready, I will move .es-419 to es-419 (and remove the es symlink). Finally I think this is the best way to do it.

About Hebrew: OK great, because I also see that [here](https://github.com/redmatrix/hubzilla/tree/master/library/intl/resources/language) we don't have he-il.

**Comment by royalterra** [comment]
@jeroenpraat I got a message from the other person is helping with the hebrew hi look have some issues for make changes. 
From: GenghisKhan At: Dec. 23, 2015, 5:16 p.m.
Hello,

I have opened Hebrew (Israel) (he_IL) because I was not able to upload an update to Hebrew (he).
The translation I focus on is Hebrew (he).
https://www.transifex.com/Friendica/teams/14920/he/

**Comment by redmatrix** [comment]
I don't see any way in transifex to make you an admin and it turns out es_419 is unselectable. It exists but we can't actually use it. In any event I've added the top 6 or 7 Spanish variants as project languages. We don't have to populate all of these and in fact I prefer that if there are minor regional differences that one uses the same "inherited strings" method I've used for en-gb and en-au ; where the diffs are minor enough that they don't require a translation project and can be handled as string over-rides for the handful of strings that require modification. @royalterra can use es_es and hopefully the other Spanish speakers can come up with something workable. Maybe es_mx should be the base for Latin American Spanish and the others can be simple diffs of that rather than separate projects. I honestly don't know why es_es couldn't be a simple diff as I recommended in my first comments on this issue, but if we require a full blown translation for es_es, you now have it.

**Comment by jeroenpraat** [comment]
Strange that you can't request es_419 on Transifex, but not use it. I did a language request for that one. Is it not in another list (a kind of request list)? Also strange that you can't add me as a maintainer. I would be happy to maintain this, so you could focus on other things. If you go to https://www.transifex.com/Friendica/teams/14920/nl/ and select my name, can't you change my role to maintainer? 

Anyhow, I think the solution I came up with is the simplest one, but that unfortunately doesn't currently syncs with Transifex. Of course it doesn't harm that you added some Spanish variants to Transifex, but I still think adding the es_419 would be the way to go. So I'm going to check with the Transifex folks how it's possible you can't add es_419.

**Comment by jeroenpraat** [comment]
@redmatrix If you don't succeed in changing my role to a maintainer, can you please add Manuel as the es_ES coordinator (like he is for es)?

**Comment by jeroenpraat** [comment]
I see the es_419 is now on Transifex: https://www.transifex.com/Friendica/red-matrix/language/es_419/

**Comment by royalterra** [comment]
@jeroenpraat we go to start again Manuel us coordinator ??? All this situation is because hi not accept the translations for Spanish not make sense in Spain Mainland . Again we start a confrontation the Spanish Spain translation is manipulate with a none native Born Spanish.
I already start the translation Spain Es and I believe I can do quiet faster I will invite my users from my .es domain to help

**Comment by royalterra** [comment]
This nightmare Start because the translations no are accurate for Spain mainland. Not one take the credit of  Manuel about his translations but not accomplish a standard for Spain . And for that is when I ask the es_Es for make one accurate for Spain . I will make you a clear example if I have a designer can only design cars from the 80 I not go to put him to make a Ferrari no make sense.

**Comment by royalterra** [comment]
from the moment you put him to coordinator I leave the translation ES-Es and consider all that post a totally waste of time . Thanks very much continue with es-es Latino version your own, is not matter try to help at the end people play around to get back to the seam point

**Comment by royalterra** [comment]
@redmatrix next time I close a issue please left close I am really tired for what I want a version es_es if the coordinator is the seam person. Sorry but I believe I waste my time.

**Comment by jeroenpraat** [comment]
This is enough. You are confusing me with lies and putting multiple issues into one. I read more about it and come to the conclusion that the standard forms of Spanish in the different Latin-American countries don't differ that much with the standard form in Spain, especially not the written form and in computers. That doesn't mean Latin-American Spanish isn’t a good idea, but it has no rush. So I'm going to link default es to es-ES again. And talk with Mike in private about Transifex.

Also closing this issue and please don't bother other people with your confusing issues any more. Tip: learn first proper English.
