### ISSUE TITLE
Strange URL in update notification in admin panel

### ISSUE THREAD

**Issue by anaqreon** [redmatrix/hubzilla#237]
What is this URL? It resolves to a strange site...

https://github.com/redmatrix/hubzilla/blob/5390594f4015eed6a1d728fb420c76cccf0d7a99/view/tpl/admin_aside.tpl#L29

**Comment by royalterra** [comment]
wuao that is a good find that url is games site

**Comment by redmatrix** [comment]
Thomas was working an an auto-update script at one point and this is left over from that effort. It is unused and was never finished. It would still be nice to have auto-updates; especially for security issues, but since we have git it has never really been urgent. We still anticipated using git, but the biggest stumbling block is what to do if the local git has local modifications which conflict with the update. Feel free to remove this code block.
