### ISSUE TITLE
Imported channel cannot be added as a connection to another channel

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#25]
I had a test channel called zot at zot-mor.rhcloud.com and deleted it.
I then imported the channel zot from red-mor.rhcloud.com. However, I did not specifically check the box saying this was the channel's primary hub.
Using the channel manager, I changed to haakon@zot-mor.rhcloud.com, and tried to add zot@zot-mor.rhcloud.com.
I got an error message, saying the channel did not exist at this hub any more.
This surprised me, as I expected to be able to add the imported channel using its new address.
Must I use channel's primary hub address to add it as a connection? This seems wrong.

**Comment by HaakonME** [comment]
Imported channel became

https://zot-mor.rhcloud.com/channel/zot6369

Notice the numbers at the end, which are not supposed to be there.

**Comment by redmatrix** [comment]
They are supposed to be there, because your hub already had a channel with a webbie of 'zot'. Perhaps it was deleted, but it takes up to a month before we can physically remove a deleted channel to give it time to notify everybody that it is gone. Because once import starts we can't interact with you, we have to just plunge ahead and try to find a reddress that will work because there's nothing else we can do but throw up our hands and tell you it failed and there's nothing you can do about it unless you're a bona fide Unix wizard and it takes a lot of hacking the database to make it right.

**Comment by HaakonME** [comment]
Thanks for the explanation!
