### ISSUE TITLE
SECURITY: Changing password does not require password

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#287]
This is in /settings/account

**Comment by redmatrix** [comment]
Are you talking about requiring the existing password before changing? Because I believe it isn't possible to set to an empty string. That is by design though we may wish to review it. It ensures that if somebody creates an account with your email that you can take ownership of the account they created and delete it - although for safety you must wait 24 hours after changing the password to delete the account.

**Comment by git-marijus** [comment]
> Are you talking about requiring the existing password before changing?

Yes.

My concern is that somebody can change the password and lock the owner out. This would not be possible if the existing password is required...

**Comment by redmatrix** [comment]
I suppose that hijacking the email address won't work if email verification is turned on. This wasn't always the case and the reason we don't ask for the old password. If email verification is disabled, we probably shouldn't require the old password. If it is, we should. We could let the admin decide, but it's really bad publicity if somebody's email gets used for an account and they have no say in the matter and end up with notification spam that they can't disable.

**Comment by git-marijus** [comment]
How does this work?
Assuming email verification is turned off:

Bob registers an account with alice@example.com and sets password to "12345". After a couple of days Alice gets email notifications from somehub.org but does not know why...

Alice goes to somehub.org and does what?

**Comment by FreeEagles** [comment]
@git-marijus is right in any system I know you need the old password for change to a new password. Also can be good a option for block the users change password is a option if we think use external implementations and bridges to Hubzilla . Users can login with a CMS or other application and bridge with Hubzilla . Like that only In one side is allow change password.

**Comment by redmatrix** [comment]
Bloody hell. So that code (especially the email notification) is left over from Friendica where we used to send you a generated  login password as email verification. OK, you're right. Let's just require the password and be done. I believe email verification is the default now but I'd have to look to make sure.

**Comment by redmatrix** [comment]
Should be fixed. Please note I had to apply the same hack as I previously did to the account/channel remove forms to preset the password field to a single space. This is the only way it seems to keep firefox from autofilling the password. They refuse to honour 'autocomplete="off"' and supply the original password no matter what you do. This is likely to result in confusion but is the only way I can find to prevent the browser from autofilling. We do perform a trim() on the input so that if folks just start typing without removing the space it will still work. If I recall there were some other workarounds to this problem suggested on MDN but none of them work and in the fine print they mention the browser may autocomplete no matter what you do - and that indeed seems to be the case.

**Comment by git-marijus** [comment]
Thanks...

Autocomplete on password forms? Jeez...
We could probably use more than one space (maybe 7?) to make it look like a real password and clear the form with some javascript on click...

**Comment by redmatrix** [comment]
It might be more confusing if it looks like a real password because then they won't enter anything (thinking it is already present) and get an error that they didn't enter the old password. With one space it may not be obvious what's happening, but they will "usually" know that this isn't their password. We might also be able to do something with a document loaded callback that wipes out the stored password that firefox insisted on adding - as long as they don't asynchornously add it after page load is complete. Anyway let's call that another issue - is this one resolved to your satisfaction?

**Comment by git-marijus** [comment]
Yes resolved... Thanks
