### ISSUE TITLE
default_permissions_role won't work with UNO

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#311]
I thought it was possible, but or it was never possible or it's a regression.

When I set 
`util/config system default_permissions_role social_restricted`

new channels are still created with the default 'social' permission.

**Comment by redmatrix** [comment]
This mode is inconsistent with the stated goals of the UNO configuration.

**Comment by jeroenpraat** [comment]
I thought it was possible, but apparently I misread something. 

> This mode is inconsistent with the stated goals of the UNO configuration. 

If those coals are to offer something familiar for people, like they maybe know from Facebook, I must tell you that on Facebook you only share posts with your friends by default. In the past posts where send by default to 'friends of friends'.

**Comment by redmatrix** [comment]
The stated goals are 1) reduce complexity and 2) ability to federate more easily with other "federated" services. social_restricted will not federate (at all) to GNU-social (coming soon). When federating to Diaspora, pump.io, w3c clients, whatever, all resources default to private permissions, so *all* uploaded images will show a lock by default when viewed from another network; webpages and files and chatrooms will also be inaccessible to members of these other networks without extensive manual configuration to undo the effects of 'social restricted' on each individual created web resource. Permissions and setting of permissions are a complexity we are doing away with in order to keep the interface usable by people with the IQ of a fish. You can still make things private using ACLs. But if private is the default, everything created by the channel requires zot permissions to access.  Since nobody but myself is responding to complaints about federation issues and I don't have time to deal with explaining cross platform permissions to everybody over and over again, we are defaulting to the configuration which provides the least number of support issues. Facebook does not have to deal with these issues since they don't federate with other services using different protocol stacks and different privacy implementations/policies.

**Comment by jeroenpraat** [comment]
Thank you for your comprehensive answer Mike. I already forgot about compatibility with 3rd party networks. Maybe an idea to put these UNO coals somewhere in short in the documentation? Have a good day.
