### ISSUE TITLE
Cover photo displayed in single post view

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#315]
When displaying a single post (aka linking to source) the cover photo (if set) is displayed. The expected behaviour is that the cover photo is not displayed when someone explicitly want to show specific content.

**Comment by git-marijus** [comment]
I see the problem... It can actaually be solved rather easy.
I wonder though if it would make sense to point link to source to `/display/mid` instead of `/channel?mid=mid`

I am not sure actually what the difference between those two are exactly.
Maybe can @redmatrix shed some light on this?

**Comment by redmatrix** [comment]
/channel presents the post in the channel environment using the channel layout and theme (which now may include a cover photo). /display is used when we want to view a post on this site and may not be able to access the source channel (which may not be on this site). I would probably add a quick hack to do $('cover-photo').hide() if $_REQUEST['mid'] is set. The reason for hide and not just remove the cover photo is because in the current implementation once you've scrolled past the cover photo there's no way to ever show it again. I think this ability would be desirable, and we should probably extend that ability to the single-post display. I'm not sure of the best mechanism to do this, but I think we should leave that option open. Perhaps as a feature for the b2tbtn plugin.

**Comment by redmatrix** [comment]
Checking in a dirty fix which blocks the cover photo on single post viewing on the channel page. We may need to sort this out again once we figure out the best cover photo behaviour.

**Comment by git-marijus** [comment]
> The reason for hide and not just remove the cover photo is because in the current implementation once you've scrolled past the cover photo there's no way to ever show it again. I think this ability would be desirable, and we should probably extend that ability to the single-post display.

That behaviour was on purpose... I thought of it more like a welcome screen which appears when somebody comes to the profile and should not interfere later anymore.

> /channel presents the post in the channel environment using the channel layout and theme (which now may include a cover photo). /display is used when we want to view a post on this site and may not be able to access the source channel (which may not be on this site).

At present we point top-level-post link to source to /channel?mid=mid while comment link to source points to /display/mid

Does anything speak against pointing top-level-post link to source to /display/mid aswell?

**Comment by jeroenpraat** [comment]
Great thanks, it works!

@git-marijus Yes, there is an issue with /display/mid, it doesn't show the channels theme when not logged in. See https://github.com/redmatrix/hubzilla/issues/251

**Comment by git-marijus** [comment]
I actually wonder if there is an issue permission wise...
