### ISSUE TITLE
After uploading a profile pic, the old icon is still shown in most places. (avatar)

### ISSUE THREAD

**Issue by Treer** [redmatrix/hubzilla#344]
Shift-refresh doesn't fix this (though I don't think users can be expected to have a shift key, or know about it these days), and loging out/in doesn't fix it. The behaviour is the same on both browsers I tried — Firefox & Brave (Chromium).

Hubzillia is tag 1.4, Version 2016-04-15.1367H+2cb04cc (new installation)

The caching settings of the apache server are whatever Ubuntu 14.04 LTS installs apache with (Mint distro).

The UX is that's there's a secondary profile icon somewhere that you can't find the setting for. Or, if you are running more than one channel, it looks like the  colored silhouette icon is always shown for whichever channel you have currently selected. I think any size of profile icon that you viewed before updating the profile pic will reliably display the old icon.

The fix for it is to right-click the image, select "open image in new tab", then go to that tab and shift-refresh.

---
![screenshot](http://i.imgur.com/wBpF8Rk.png?1)

In this screenshot I have two channels, both channels have uploaded profile images. All 3 of those images used to still display as the colored silhouette, but I performed the new-tab-shift-refresh trick on the top channel, so now it shows the photo. The news channel is currently my selected channel.

**Comment by Treer** [comment]
In uploading more profile pics I caught the info hint popup that says "clear your browser cache if image does not update", so I now assume this is an already known issue and currently considered either too hard to fix or not sufficiently urgent. Hopefully googling it can lead people to the two solutions described here.

**Comment by redmatrix** [comment]
There is a trade off with system performance and privacy expectations. We once had non-cahced images which allowed you to change a photo or privacy settings of a photo at any time and the results would be instantaneous. There were many complaints because it means we hit your server for every image on every page, always. Small sites were getting hit hard. So we put a cache in place. With the cache, we can't notify you that a photo has been updated because the server never sees a request for it. The browser just grabs it from the cache and never asks for it from the server. The best compromise we could come up with between the competing factions is one day cache time. 

On pages with the large profile photo in the sidebar we've done a reasonable job  of updating immediately because we add the photo update timestamp to the URL. This works consistently for me on firefox, but it doesn't work for some people with the same or different browser configurations. Unsure why not since it always works for me so I have nothing I can track through to find a problem. If this worked consistently it would be a good idea to extend it to other uses of the profile photo locally so the change would appear to be instantaneous. But one also must consider the propagation to other sites, which also is not instantaneous and their 24 hour cache time might have just started. What we normally tell people is that in a decentralised, distributed world, things don't always happen instantly. We do the best we can, but photos seem to take a day or two before they are updated everywhere. So you can disable the cache locally, but your friends will probably have caches and they won't see your new photo until tomorrow. We're always open to suggestions on how to improve this, but this is how it all works today.

**Comment by Treer** [comment]
> On pages with the large profile photo in the sidebar we've done a reasonable job of updating immediately because we add the photo update timestamp to the URL. This works consistently for me on firefox, but it doesn't work for some people with the same or different browser configurations. Unsure why not since it always works for me so I have nothing I can track through to find a problem.

I've seen something that *might* be described that way, I might be able to reproduce it and investigate, is there a link to that issue? Was it a Friendica issue or is it new to how Hubzilla does things?
