### ISSUE TITLE
RSS feed - inconsistent display of content

### ISSUE THREAD

**Issue by AFlowOfCode** [redmatrix/hubzilla#346]
I've tested RSS feeds and found them to be inconsistent or problematic in the following manners. I'm using examples from the hub I'm on, but testing has shown it is spread across numerous implementations. I can provide specific channel examples on other hubs, or they can be found easily after viewing several feeds.

1. Not displaying any entries
http://hub.spaz.org/feed/dbene
Nothing displayed, likely due to only having older posts. At some point in the last month or so, the RSS seems to have reset and all previous entries were lost from the feed. This can be seen in just about all channel feeds I've checked. Maybe this has something to do with the $a replacement, as many feeds do not go beyond March 31. Not sure. 
IMO the RSS feed should display all posts regardless of age. If there needs to be a limit it should be numerical, so that eg when 100 posts are on the feed, the oldest start getting bumped. Perhaps there is a method to simply rebuild the feed. I am unaware of it.

2. Only displaying post titles
https://hub.spaz.org/feed/spaz
The content from the posts is missing, but feed shows whether a user is attending (for events) or has liked the post. Note that this does not relate to the type of post being an event, as the problem also exists for non-event posts.

**Comment by redmatrix** [comment]
1. There are two possible culprits here. Some time ago there was an issue limiting the number of returned posts, and the feeds were presenting all posts ever created on that channel. This caused some serious problems as some channels have several years of content. A short term fix was provided to limit the starting date to a month until the real reason was found. The real reason was found and ultimately fixed but we neglected to remove the short term fix. I will check this in shortly. 

It is also possible that the channel owner has restricted permissions on their stream. The public feed returns nothing if the channel does not post publicly by default. This is probably not the case here and is probably the bug mentioned, but I'm mentioning it for completeness. Many folks have private channels and their public feeds are totally empty. 

2. Likes and attendance info are sent as ActivityStreams. The content for these activities is simply the statement that xyz liked something or is attending. The full content is provided in the activity actor, verb, and object/target per the original ActivityStreams spec (Atom version since there are now other versions). Most software does not display this content but internally converts these to the platform "like" or "attend" indications.  However the text statement is provided for generic Atom processors that do not understand ActivityStreams (or do not have special handlers for these particular activities) so these items can be presented by basic feed readers; hence the activity statement is human-readable. Unless I've missed something in your issue description I don't see any bug here.

**Comment by AFlowOfCode** [comment]
Sorry I wasn't totally clear on #2, the like / attendance info was meant to be extra data but it was confusing. 

The problem is the content of a post is not being displayed. On https://hub.spaz.org/feed/spaz for example, one can see the titles of the posts, but no content from that post is displayed. When you click on the title, you are brought to the HTML version showing all the content. This is a newer development as well, because previously the RSS was displaying the contents of posts with no problem. I believe this also changed around the same time as what seems to be the cutoff for old posts.

This problem is inconsistent, many feeds are fine, many are not. Here is another channel showing what may be the same problem: https://grid.reticu.li/feed/andrewmanning  .. look at the feed, then look at the channel. For this particular channel, there are no post titles, so there is even less idea of how to figure out what you're looking at. The feed is useless as is, there are only dates and whether someone liked something, and it appears somewhat randomly selected. This one might be related to privacy settings, I can't tell.

**Comment by redmatrix** [comment]
It appears you're seeing two different issues with #2. We made some changes recently to the way events are formatted in feeds to make them directly compatible with the format used by GNU-social. Besides some other minor changes, GNU-Social also provides a 'summary' field which is set to the event title. Many feed readers look for both 'summary' and 'content' and if 'summary' is present, they ignore 'content'. That appears to be happening in this case with your feed reader (I've duplicated using Firefox pointing at the feed - it ignores 'content' completely for events). This behaviour will vary by feed reader (they can choose which field to display if both are present), but it is quite common for content to be ignored if there's a summary. I can easily comment out the line that generates the 'summary' field, but I'm not certain if this would break GNU-Social event compatibility. GNU-Social events are somewhat new and it's possible they aren't aware that the event content will be ignored by most feed readers. I'll comment it out for now (since we don't need it for anything) and make a note why I did so; because we are in the process of providing stronger protocol integration with GNU-Social - and this decision may need to be revisited and perhaps reversed.

Andrew's feed is a bit more troublesome. The SQL queries we use should always provide a parent post, followed by replies/likes/whatever to that parent post; and the parent post here is completely missing. That is most definitely a bug; but since it seems to somewhat random in nature (my feed seems to work fine), I'll have to poke around and try and duplicate it so as to pinpoint the cause.

**Comment by AFlowOfCode** [comment]
Ok I see. When creating an event there is no option to input a summary and it appears to simply be duplicating the title, making it extraneous (worse, since it actually blocks the content). 

Generally speaking, a summary field seems more appropriate for a longer post rather than an event listing. However if the summary field is required for compatibility, perhaps it could be populated by the event description field instead. There could also be an option for summary in event creation, but if left out, again perhaps populated by the description since ultimately there is no purpose in duplicating the title.

**Comment by redmatrix** [comment]
In fact we create the post title from the event summary. We call it 'title' on the event form just for consistency - as that is what people are going to see in event postings. There may be no easy solution as the activitystreams spec for events dictates that one use ical/vcal fields wherein summary is *required* and differs from description which isn't required. 

I seem to recall I confronted this 5-6 years ago when I created the ActivityStreams events and didn't follow the spec precisely for this reason; it was very vague and at that time nobody else was providing activitystreams events so there were no clear models of how to do it correctly.  I think what I may need to do is change the namespace for the summary field so it's tagged as a calendar field and not an atom field - and then accept atom_entry:summary if there is no xcal:summary. The end result will be that our feeds should be spec compliant but they may not be GNU-Social compliant; and you should see event content again. Then I'll have to open an issue with GNU-Social to sort the compatibility mess it raises.

**Comment by redmatrix** [comment]
Both issues should now be fixed going forward. I haven't yet contacted the GNU-Social folks.
