### ISSUE TITLE
Sabre DAV: headers already sent warning

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#385]
Hi I see there a issue in PHP Warning:  Cannot modify header information - headers already sent by (output started at /data/www/view/php/default.php:6) in /data/www/vendor/sabre/http/lib/Sapi.php on line 63

Possible can be solve with add at the top of the file ob_start();

**Comment by git-marijus** [comment]
Yes i also see this if visiting /cloud/username

**Comment by git-marijus** [comment]
adding `ob_start()` before `$server->exec();` does indeed silence the error but it renders the page slightly different (to much padding-top for section and aside)...

i tried to add ob_start() to boot.php also silence the error but still renders the /cloud page different all other pages look normal though...

**Comment by git-marijus** [comment]
hm... thats wired...
if `ob_start()` is added `#nav-notifications-template` from hdr.tpl is loosing its `style="display:none;"`
it is than visible behind the panel... hence the misplacement of the content...

**Comment by git-marijus** [comment]
it seems like HTMLPurifier kicks in somewhere where it shoudn't...

**Comment by redmatrix** [comment]
There shouldn't be any html purification in that module. I haven't yet dug into this but there warnings in the upgrade doco that the internals of the DAV Browser component (which we basically copied and partially rewrote) changed considerably between versions 1.8 and 3.0. All I did at the time of upgrade was silence a class warning from the auth component iirc which we were using in a non-standard way. What we probably need to do is figure out how our current Browser (or actually the old Browser base class) differs from the new base class that has shifted beneath our feet.

**Comment by git-marijus** [comment]
I found out that Sabre sets `content-security-policy:"img-src 'self'; style-src 'self';"` by default now. This removes the style info from our html.

I think we need to work with ob_start() since we set headers in construct_page() and sabre sets headers later, to silence the warning (except i am overseeing something completely). 

For the rendering issue we can either overwrite content-security-policy headers in generateDirectoryIndex() or we simply move the style information to style.css

The second solution is the better one i guess...

**Comment by git-marijus** [comment]
Ok... the fix did not really work... Sabre's content-security-policy headers also disturb the functionality of the file edit tool (pencil) we use in /cloud... 

Overwriting sabre's headers with `$this->server->httpResponse->setHeader();` is not an option i guess since this would also overwrite our headers...
