### ISSUE TITLE
Ability to set permission for OpenID uris

### ISSUE THREAD

**Issue by strk** [redmatrix/hubzilla#408]
Is there any plan to add the capability to grant access to a published resource to the owner of an URI via OpenID ?

**Comment by redmatrix** [comment]
There are such plans, but we're also looking at the bigger picture and trying to envision how this will fit with authentication via other means (Friendica remote authentication, OIDC, OAuth, and in particular SAML). Nobody is actively working on this piece at the moment, but we expect to get back to it after our architecture upgrade winds down. The bit you are probably most interested in is also the bit where we need a fair bit of work - tying a remote authenticated identity to a "federated identity" so that they can be considered one and the same. We'll probably require identity assertions to prove for instance that a given openid holder is also a Diaspora or Friendica channel which we are already connected with.

You can in fact add an openid principal to an ACL (manually in the database) and this works today, but there is no way in the UI to add it since we typically don't connect with openid identities as friends/contacts/connections. There is also today a working permission class called 'anybody authenticated' which honours openid authentication.

**Comment by strk** [comment]
I don't know much about FRDN, ZOT and the others, but couldn't
authentication be just based on w3c standard protocols like OpenID ?

Then people following links from friendica could still pass their
"profile url" to others as they do now, and from the "profile url"
(possibly expanded from webfinger, if needs be) an openid indication
could be found.

So it'd be a matter for all federated nodes to _act_ as OpenID
providers and for them all to use OpenID (when available) to
authenticate people referenced by url or webfinger.

I basically want to be able to post something that's only visible
to people I recognize by their controlled URL (ie OpenID)

**Comment by redmatrix** [comment]
It's on the project roadmap and has been for many years now. Are you volunteering? If not, it will remain on the roadmap until somebody does. I'd highly recommend trying to work with oidc or saml. Traditional openid has been dead for a few years. If your solution requires clicking on approvals and permission granting windows before you can load a photo in your stream it's not going to work easily with our project. You might have hundreds of privacy protected photos in your stream. Also, if it doesn't work with nomadic identity (nothing does, really), it won't work with hubzilla. But you might be able to make it work with Friendica.

**Comment by strk** [comment]
Most OpenID providers allow you to remember the choice of your
approvals, so the "clicking" problem would be mitigated by that.

The concept of nomadic identities is still not clear to me,
and no, I'm not volunteering.

**Comment by redmatrix** [comment]
Let's say thirty people send private photos to you and you've never authenticated on their site before. That's a lot of clicking before you can see your stream. Normal people will not tolerate this. It's a lot like the self-signed cert problem which plagued Friendica for years. I stopped using it for a few years because if I accessed my account from a new computer (I work in student labs with hundreds of machines), it took half an hour to load my stream after clicking away all the warning dialogs. It only became useable again after LetsEncrypt removed the objection to having signed certs. You may be OK doing such things to grant approvals and see your stream, but my mom and sister won't.

Nomadic identity simply means your account is mirrored on different systems and isn't tied to a particular DNS  location. If your primary server goes down (temporarily or permanently), you can pop up on any other server and carry on as if nothing happened. This wreaks havoc with traditional decentralised services that base who you are on what server your account is on. In the case of openid, it means you can have more than one openid handle and different authentication servers and they all refer to the same account. This concept isn't built-in to openid and trying to make it play nicely is a huge challenge. If it was easy I would've done it.

**Comment by strk** [comment]
These "thirty" people would have need to be "approved" by myself before
I could receive private photos, right ? Or it could become a private
spam nightmare...

Could my server then act as the OpenID provider so it remembers who
I trust by looking who I marked as approved ? There would then be no
clicks on streaming.

**Comment by redmatrix** [comment]
I don't think you're following the real problem. Because no, you could be viewing the 'public stream', but somebody posting photos in that stream could have *photo permissions* which are different than the post, and be visible to say 'anybody authenticated'. This includes anybody authenticated with openid. To figure out if you're authenticated, there's an auth hint attached to the photo URL. And it goes out and authenticates you and loads the picture (or a substitute 'permission denied' photo). Let's say you work around this by embedding the photo as we did in Friendica. OK. What if it's a video? You're going to embed an entire two hour video into my stream to get around the auth challenge? Probably not. that's why we have cross domain web auth. 

I know people think that I did all this stuff to thumb my nose at standards, but that's simply not the case. The standard protocols don't fit the requirements and use cases for these features, full stop. We can use such standard protocols in places where it's appropriate to use them and where the features meet the use cases of the protocols. 

In any event, I will be doing some work on the permission system in the next few weeks in an effort to make it more easily extensible. I will keep openid use cases in mind as I'm doing this work. It will not replace the existing "magic auth" backend with an alternate protocol or choice of protocol, but it will probably allow you to more easily attach an openid identity (or saml identity or facebook identity or any identity) to an ACL, which was the original issue here. If you or anybody else wishes to work on ways of using alternate identity providers as plugin url authenticators, go right ahead. The platform is extensible by design. I'm not saying there couldn't be clever ways to make such services work, but I did think about them (a lot) in the initial design and couldn't come up with any way at the time that was seamless, as these protocols were designed around different use cases. Openid autnenticated viewers and openid viewers *in ACLs* are possible. But their interactions will in many cases not be seamless and at the present time requires manual fiddling of the ACL - but it works today. I'll look at ways to get around the manual fiddling. If this isn't good enough for your needs, the project is open source.
