### ISSUE TITLE
Hebrew Translation and Translators harassed in Transiflex

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#413]
I will like to know when the hebrew translation go to be include in HUbzilla
and some one can tell me what go in on again and again. Is this a project with political or religious views or is a free open project?

GenghisKhan Helping the translation of Hebrew already  complaint in Transiflex of be harassed . That is not first time happens here already some people act very bad educate and aggressive again my self .

I will like to think hubzilla is a free open source project with not political or religious views if not please some one make that clear and we will make a fork and move on .

People not need to be attack for religious, racial, .... I believe that is one of the first stamens of the Human Rights Declaration

**Comment by redmatrix** [comment]
The process for including a translation (or any other code change) involves issuing a pull request to the project repository. See help/Translations on any site. 

"The project" has no political or religious affiliation or views and as a project we do not tolerate lack of respect. I must point out that respect works in two directions. The best way to have technical discussions is to discuss the technical issues and refrain from personal attacks based on religious or other grounds. Some people tend to see persecution where none is present and become aggressive towards others as a result of this perceived persecution. This usually is counter-productive. 

In this case, the reason no Hebrew translation has been included in the project is simply because nobody has issued a pull request for including a Hebrew translation in the project. Turning this technical issue into a religious issue is counter productive.

**Comment by redmatrix** [comment]
I've tried to find one of the mentioned conversations on Transifex but haven't been able to; and I can't offer much in the way of practical advice for dealing with abusive behaviour on that forum. Most social applications have tools for blocking/ignoring hostile conversants, but I don't believe Transifex considers itself a social application and may not have thought much about the issue. One may need to "manually" ignore those that are abusive.

**Comment by royalterra** [comment]
First i not have any other intentions but a guy is helping the project of translation report the harassment. hi make clear in one of the redmatrix discussions. 
Anyway now about the translation I review and ask months ago to be include in transiflex in a private message to the administrator.

**Comment by royalterra** [comment]
Ok That guy make clear everything in Transiflex . And not one for Hubzilla is involve . Anyway hi can make next time more information like hi make his first post is like a Hubzilla member cross de line.
I apologize for have doubts and happy now all is clear
