### ISSUE TITLE
Translation Help need

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#425]
I push the translation and I believe is working according to https://github.com/redmatrix/hubzilla/blob/master/doc/Translations.md but is not 

Anyway I see I have the file hstrings.php but in other translations is strings.php I imagine there already changes is not documented and I follow a old setup can any one help me thanks

**Comment by redmatrix** [comment]
The pull request was for redmatrix:master - redmatrix is essentially an abandoned project tree at this time. Pull requests should be made to hubzilla:dev, where they become part of the normal development flow. They won't appear in hubzilla:master until the next release. 

You can issue pull requests on multiple branches if you want a new language to appear quickly. We currently have dev, master and 1.8 RC which is the next release candidate. I expect it will go live tomorrow. 

For hubzilla, you would use the files hmessages.po and hstrings.php .  Redmatrix uses messages.po and strings.php. The strings are similar but there have been hundreds of changes since redmatrix.

**Comment by redmatrix** [comment]
Ignore the last message. I've tried to straighten out the hebrew translation and have committed it to dev, 1.8RC, and master.

**Comment by royalterra** [comment]
Hi Thanks for the help. I will send next contributions to the hubzilla:dev I have be away now many weeks for personal family reasons and I not follow much the project
