### ISSUE TITLE
Apps usability

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/hubzilla#446]
- disabling a plugin does not remove its app(s)
- once an app is deleted we can't ever bring it back it seems since it's marked deleted in the db

**Comment by royalterra** [comment]
The issue is in Addons folder still is a copy of the APP 
bye example you remove one APP repository front the HUB but still in the folder Addons there a copy you will need to delete manually the add-ons with rm -r folder-addon-name to delete 
Seam issue with Themes you delete the git repository but Themes still show up that case you need to go view/themes and delete the folders keep in mind always keep redbasic theme or you are done
