### ISSUE TITLE
wrong navigation?

### ISSUE THREAD

**Issue by hypergrove** [redmatrix/hubzilla#504]
When looking at a channel not my own, when I touch the 'gears' icon on MY toobar, then I see the apps for the other channel, not the apps for my own channel. Since the icon is on my toolbar, I believe it is confusing to see information displayed that is not my own.

**Comment by jeroenpraat** [comment]
Confirmed. This is indeed confusing. Possible solution is to disable the apps icon when viewing a remote channel or to redirect it to the viewers own apps. I prefer the first solution.

**Comment by zotlabs** [comment]
Different sites may have different apps available, and may make these available to visitors to that site. For instance on my site I've got a guitar chord app. If you visit my site you should be able to use it, even if it doesn't exist on your own site. I would suggest that it isn't "your" toolbar and this may be a perception problem. It changes all the time depending on who you are and where you are and what permissions and what resources are available to you.

**Comment by zotlabs** [comment]
I note that Apps are disabled when running a 'basic' server.  This only serves to point out that what is in the toolbar is under control of the site you are viewing. I can put dancing girls on the toolbar and use a different icon for Apps and there's nothing anybody else can do about it. It's my site. If you visit my site, you'll be seeing my site and whatever I choose to display - it's not yours at all. 

We once had the ability in the chanview module to load other sites in an iframe; which did keep "your toolbar" at the top (and the site toolbar just below it). Even though it was optional, people hated it (there were two toolbars which behaved differently stacked on top of each other) and this feature was eventually disabled.  We did this to ease the transition for Diaspora folks; who use a completely different network model (they actually do own the toolbar since they never leave their site).  You would be welcome to revive the iframe mode and even provide it as the default for your site as long as it is not the default mode for the project. We've been there, done that, and didn't like it.

Providing the same model as Diaspora is not negotiable; as it favours large sites over small sites. Your site must store all profiles and public posts for everybody you discover in the network and this tends to make small or personal servers impractical. In the Hubzilla network we have a level playing field.  If you are running a server farm or a Rasberry Pi the experience is exactly the same.

**Comment by elvecio** [comment]
"This is indeed confusing. Possible solution is to disable the apps icon when viewing a remote channel or to redirect it to the viewers own apps. I prefer the first solution.". I absolutely disagree, I do not see any confusion, perhaps it can confuse people who come from the diaspora-model, which is in my opinion  completely outdated and far-fetched, they never leave their primary site, while we have the possibility, and thankfully, to travel to other sites without having to log-in or do other things, at best we can authenticate in it. When I go to the home of a person I want to see his house, and not the 'virtual vision' of his house.

**Comment by jeroenpraat** [comment]
@elvecio I almost agree with you, but what are the benefits of the app page for a remote member? We already remove everything from the top left toolbar (except the menu and home icon) because those functions won't work for a remote member. The apps page usually has some apps that can be used by a remote member (mostly games and utils), but they (mostly) can be found on the members home hub as well. The difference is that the home hub has them all (if enabled) and not a few like on the remote hub. This can cause confusion, because the member maybe assumes that almost all its apps are gone or not working (like the post app).

The other two icons on the top right don't have this problem, because the content is usually the same between the home and remote hub (except that you can filter on the current hub in the directory).

**Comment by jeroenpraat** [comment]
Another thing the OP says is "Since the icon is on my toolbar". Well that's something members have to learn from the start. That it is a dynamic universal toolbar that is not yours, but part of the Hubzilla application.

**Comment by jeroenpraat** [comment]
Of course there a few hub specific apps available and probably/hopefully even more in the future. But most of them are similar as your own hub and that can cause confusion to some new members. The best thing I can come up to avoid this, is to change the string 'Apps' to 'Apps on https://hubzilla.nl'. But if this is overdone, than we better leave it like this.

**Comment by git-marijus** [comment]
If you look to another channel on another hub it's **not** your toolbar allthough it might look similar. It remains your toolbar as long you stay at your 'home' hub. It is pretty easy to distinguish those two since you don't have most of the left-side tools if you happen to land on another hub...

I don't think this is an UX issue.

**Comment by elvecio** [comment]
...and also it is easy to distinguish because the address in the browser changes, while for example in software like diaspora will notice that the address is the same (same site). So a person a little bit careful to note right away that the address is changed. You realize immediately that 'you are not at your house'.

**Comment by Vertux** [comment]
First, I am very new to Hubzilla. When i read this conversion my first idea was to give remote and local toolbars/apps a different color indicator e.g. red for remote and green for local ones.

**Comment by zotlabs** [comment]
I'm calling this invalid - it is working perfectly in the manner it was designed.
