### ISSUE TITLE
Map App is defunct due to changed mapquest policy

### ISSUE THREAD

**Issue by blausand** [redmatrix/hubzilla#508]
Never rely on closed source stuff :/

**Comment by zotlabs** [comment]
What map app? We don't have any project apps or plugins which link to mapquest that I'm aware of.

**Comment by jeroenpraat** [comment]
Mapquest offered free Openstreetmap tiles, until a while ago. Gnome maps had the same problem. So what Mike said, it's a hub issue. You have to ask your hub admin to change to another tile server.

**Comment by jeroenpraat** [comment]
Why reopening this? It is clearly not a code issue, but a hub configuration issue.

**Comment by zotlabs** [comment]
I think we should leave this open as a courtesy pending more insight into the issue. I don't think we have a code issue but without a bit more detail I cannot say this definitively.

**Comment by jeroenpraat** [comment]
I think we should close issues as soon it's clear we fixed them, we won't fix them or if they are invalid. That's what I learned when I worked on a support desk myself. That will keep the issue list manageable. But it's no big deal if you like to keep this one open.

**Comment by anaqreon** [comment]
This is likely referring to the map plugin I wrote, which is not an officially supported plugin, but has the problem described. I replaced the tile source from Mapquest with OpenStreetMap but I have not updated the publishedplugin because I am in the process of revising it for integration into the official hubzilla-addons repo. Ultimately the tile source should be configurable through the map admin settings, but for the foreseeable future it will be OpenStreetMap.

**Comment by blausand** [comment]
@anaqreon thanks for showing up. I was indeed somewhat abusing this issue tracker since the problem was obviously outside hubzilla core's scope.
Hope i could motivate you to fix and improve. Geobased content is a huge player in future social networks' feature landscape.
