### ISSUE TITLE
Private profile visibility

### ISSUE THREAD

**Issue by ilu33** [redmatrix/hubzilla#513]
Private channels should not show up when a "random profile" is selected.
A possibility to disable the "random profile" selector would be an alternative.

**Comment by git-marijus** [comment]
What do you understand under a private channel?
A channel which is hidden in the directory?

**Comment by ilu33** [comment]
I can't see any change.
For me a "private channel" is a channel that is not visible if you are not a friend or at least on the same server. By "not visible" I mean not visible at all, not even the channel name. We are still struggling with understanding hubzillas concepts but whatever we did, all channels always showed up via "random profile". Only public channels should show up there. A channel that chose not to be in the directory should never be eligible for "random profile".

I admit that we are still a bit confused about channels and profiles but we'll work on it - as soon as the database gives us a chance :-)

**Comment by git-marijus** [comment]
The change is about not showing channels which are hidden in the directory.
Note that this change is not yet in master but in dev branch.

**Comment by ilu33** [comment]
Give us some more time please.

**Comment by ilu33** [comment]
Now social-private channels don't show up in the local directory and don't show up via random search. Social-restricted channels show up in the local directory and via random search. That's what you meant right? I guess I was confused because I expected that the "Local directory" stayed local only but in reality it's part of the network directory. So we'd have to think about how to get a local only directory.

**Comment by zotlabs** [comment]
In this network, channel names and profile photos are public; and this is non-negotiable. There are several important reasons for this. We can hide you from the directory, but if you interact with others, these interactions will leave footprints. We need to be able to assign these footprints to something, otherwise all hidden channels would have to be treated as one single anonymous channel since none could have any distinguishing characteristics. E.G. you could not use them for access control. 

You can configure your site as a standalone directory server, and this takes your site "off the grid". This tends to hide even your public channels from the global directory. We can still index them if somebody within the grid connects with them, but we mark everything from off-grid sites as hidden and keep it from showing up in the global directory. It sounds like you might wish to use this option. You can also create entire mirrored directory realms outside the public grid if you wish to network a collection of sites off-grid.

**Comment by ilu33** [comment]
Thank you for this explanation. I can understand now that the channel name always needs to be "public" - but why also profile photos? This forces everybody who is concerned about privacy to never use a real photo on any channel. Just a thought.

On topic: I'm still wondering whether things really work as intended. Our server is configured standalone and also "block public" is activated. But the behaviour is not "off the grid" as you described. It needs the keepout plugin to reach the desired effect. Also polling doesn't work server-only but includes the grid, which is a bit annoying during testing because of all the error message we get.
In the end this doesn't really bother me since "standalone" is only temporarily during testing. But I'm trying to test everything as much as possible.

**Comment by zotlabs** [comment]
> Also polling doesn't work server-only but includes the grid

There's an option to disable importing public posts in the admin section. You probably want to have this disabled for testing. We still poll connections you've made offsite to make sure we have current info for all of them.

Anyway, with regards to secrecy; there are two modes and they are almost polar opposites. We provide decentralised *privacy* as opposed to *anonymity*. Privacy requires identity; we must know who the observer is in order to decide whether or not they should be allowed to see something. Anonymity assumes that all information has been compromised and the only way to speak freely is to hide who you are.

The issue with photos probably isn't important today, but is critical as the network grows. If there are two people named 'Tom' you need to be able to distinguish which one you wish to show or hide something.  In our private modes, there is very little that is disclosed about you - in fact only the name and photo and a URL to where we might learn more. But if you visit that URL, the channel may be configured so that literally nothing else is available. I'm not sure what you think you're protecting by hiding a photo that's attached to your name if there's nothing else that can be discovered about you. 

I'm not completely opposed to replacing the photo with 'rainbow man' (our default profile photo) when showing a post or comment from a hidden person in the stream. But this doesn't scale if you end up with two hidden channels both named Tom. You'll have issues with privacy because identity might be ambiguous in certain cases, and privacy is our core feature. In order to represent an identity to humans, we use the typical social network 'badge' which is the profile photo, the name, and when either is clicked it will go to the channel home page.

**Comment by ilu33** [comment]
Photos don't help you to avoid the identity problem. 3 channels named "Tom" all might use the rainbow man. The only thing to differentiate them is the channels address because that's unique. So I totally understand why you need to keep the channel name and address public (which I did not understand in the beginning). But photos can be (and already are) scanned by biometric algorithms and that's a security risk I would never advice anybody to take. Photos also might be faked (identity theft included).  
However anybody would decide that for oneself: We are trying to find a social tool we can recommend to schools and youth organisations. That's why we have to think about paedagogic and legal concerns. Students might want to use real names for channels but under these circumstances they can't be allowed to do so. But if teachers are legally forced to forbid real photos too (which they must do if profile photos go public) most of the appeal would be gone. We can't really recommend Hubzilla for youth organizations if we can't ensure that profile photos stay private (or get replacecd by something generic).
However facebook handles these things is unimportant because FB can't be forced to abide our laws but everybody working with youth has to abide.

**Comment by zotlabs** [comment]
All I can do is provide the technical issues we've encountered and explain the decisions we've made.  The project is open source.  I would suggest that this might best fall under a server_role (perhaps named 'edu' or something like that) which presets all the privacy settings required for a K-12 enterprise and also disconnects them from the larger hubzilla network. If (completely) anonymous identity information is limited to those using this role, I would have no objections.

**Comment by ilu33** [comment]
Your mention of "K-12 enterprise" confuses me. This seems to be some software suite, does it have anything to do with hubzilla? And is there documentation in regard to fine tuning server_role? And I think I have problems correctly understanding your last sentence (english is not my native language). But this discussion doesn't really belong here any more. Can I contact you via pm on hubzilla?

**Comment by git-marijus** [comment]
I might be missing the point completely here but...
Isn't our multiple profile feature exactly what you are looking for?
You could use an anonymous image for your default profile which is visible to everybody on the internet and you can have a second (or 3rd, 4th, etc.) profile with your personal photo which is only visible to your contacts or a selection of your contacts...

**Comment by ilu33** [comment]
I still don't completely understand the relation between channels and profiles. I will test this further tomorrow, good hint. Maybe I totally missed the point :-)

**Comment by git-marijus** [comment]
The short answer is: a channel is about what, a profile is about who.
