### ISSUE TITLE
greater compatibility between the freeweb networks...there are still hubs and channels using redmatrix

### ISSUE THREAD

**Issue by elvecio** [redmatrix/hubzilla#542]
we need to change 'youtube' with 'embed' here https://github.com/redmatrix/redmatrix/blob/ffb537c35d8f2fe3e208ffb88281d2e8ecafaa3a/include/bb2diaspora.php

and also 'vimeo' with 'embed'....

    //$s = preg_replace("/([^\]\=]|^)(https?\:\/\/)(vimeo|youtu|www\.youtube|soundcloud)([a-zA-Z0-9\:\/\-\?\&\;\.\=\_\~\#[zrl=https://zotland-myzot.rhcloud.com/search?tag=%5C%25%5C%24%5C%21%5C%2B%5C]\%$\!\+\[/zrl],]+)/ism", '$1[url=$2$3$4]$2$3$4[/url]',$s);
    $s = bb_tag_preg_replace("/\[url\=?(.*?)\]https?:\/\/www.youtube.com\/watch\?v\=(.*?)\[\/url\]/ism",'[youtube]$2[/youtube]','url',$s);
    $s = bb_tag_preg_replace("/\[url\=https?:\/\/www.youtube.com\/watch\?v\=(.*?)\].*?\[\/url\]/ism",'[youtube]$1[/youtube]','url',$s);
    $s = bb_tag_preg_replace("/\[url\=?(.*?)\]https?:\/    \/vimeo.com\/([0-9]+)(.*?)\[\/url\]/ism",'[vimeo]$2[/vimeo]','url',$s);
    $s = bb_tag_preg_replace("/\[url\=https?:\/\/vimeo.com\/([0-9]+)\](.*?)\[\/url\]/ism",'[vimeo]$1[/vimeo]','url',$s);

and maybe here https://github.com/redmatrix/redmatrix/blob/ffb537c35d8f2fe3e208ffb88281d2e8ecafaa3a/include/bbcode.php the same changes

redmatrix  does not have problem with 'embed' but hubzilla has problem with  'youtube' tag...thereby returning everything to **embed** even in redmatrix should not create problems. Right?

**Comment by zotlabs** [comment]
This probably belongs to the redmatrix issues list. I'll leave it here in case anybody wants to pick it up, but redmatrix is really on morphine drip at this point. We're only fixing the most critical issues. This is hardly critical. 

Another reason to leave it here is that perhaps we want to translate redmatrix bbcode to hubzilla bbcode when it arrives at hubzilla and leave things alone elsewhere. This is probably best done with a plugin since we're trying to remove all code from hubzilla that references corporate services. The only construct that's slightly tricky is [youtube]xyz123[/youtube] containing only the video id since you have to rebuild the youtube url.

**Comment by zotlabs** [comment]
Fixed in the latest std_embeds plugin. Available for Hubzilla 1.14RC and later.
