### ISSUE TITLE
change password does not work

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/hubzilla#543]
server: lighttpd

I will

http://hubzilla.mamalibre.com.ar/settings/account

and redirects me to

http://hubzilla.mamalibre.com.ar/network

[more info](http://hubzilla.mamalibre.com.ar/channel/mama21mama/?f=&mid=48a8ca40656469b1ff14e287fd6415bad24e66915d7e2a56530f11e39ea47efb@hubzilla.mamalibre.com.ar&zid=mama21mama%40hubzilla.mamalibre.com.ar)

**Comment by elvecio** [comment]
I tested minutes ago, and it works. 
When you go in /settings/account you need to write the current password in the first line, and the new password in the other lines.
It worked with me , without problem (hubzilla 1.12+6dc7523 ).
ps: you need to go in /settings/account after /network, and after the change you will be  in /settings/account again, but it works, you can use the new password in the next login ;-)

**Comment by mama21mama** [comment]
>> [Video](http://upfiles.mamalibre.com.ar/files/password_no_work.webm)

**Comment by elvecio** [comment]
I don't understand...when you try to go in /setting/account you can't because it will go in /network??
frankly, I think it is just your problem, it works for me very well.
In this case it is your own personal 'bug'. Why not try to join another site (not your own) and see if it happens again?

**Comment by mama21mama** [comment]
lighttpd.conf
```
## modules to load
server.modules = (
	    "mod_proxy",
	    "mod_status",
            "mod_access",
            "mod_alias",
            "mod_compress",
#           "mod_fastcgi",
            "mod_cgi",
            "mod_rewrite",
            "mod_redirect",
#           "mod_usertrack",
            "mod_expire",
#           "mod_secdownload",
            "mod_flv_streaming",
#           "mod_evasive",
            "mod_accesslog"
#           "mod_simple_vhost"
            
            
)

$HTTP["host"] == "hubzilla.mamalibre.com.ar" {    
    server.kbytes-per-second = 0
    server.error-handler-404 = "/index.php"
    server.document-root = "/media/Disco160/www/hubzilla.ml"
    #server.document-root = "/media/Disco160/www/mantenimiento"   
    server.dir-listing = "disable"   
    url.rewrite-if-not-file = (
	 "^/(robots.txt)" => "/robots.txt", 
         "^\/([^\?]*)\?(.*)$" => "/index.php?q=$1&$2",
         "^\/(.*)$" => "/index.php?q=$1"
    )
       
}
```

I have everything as it says the installation.

**Comment by elvecio** [comment]
sometimes, when I have some similar problem, I solve everything with a very good **cleaning of cache** ... I do not know if this is your case.

**Comment by mama21mama** [comment]
I did that and nothing remains the same.

**Comment by zotlabs** [comment]
This is a very unusual problem. I've created an account on your system to try and debug it, but I'm unable to figure it out. There appears to be an error loading the submodule (settings is the module, account is the submodule). The error appears to be getting trapped at the webserver level which is redirecting to the server root (http://hubzilla.mamalibre.com.ar) and this is in fact redirecting to /network.

You may need to look at your lighttpd log files to see if any errors are being logged. Also please check the ownership and permissions of the directory Zotlabs/Module/Settings and all the files contained inside it to ensure they are the same as the files in Zotlabs/Module.  

What is truly bizarre is that when /settings is invoked without any arguments, it is successfully opening and executing the submodule Zotlabs/Module/Settings/Channel.php; however if you try to visit /settings/channel (which executes the same code) it cannot do so and redirects back to the top. 

I doubt that it could be your PHP version, but this would be useful to know since we don't have any better ideas at the moment. I don't know anybody else that is currently running hubzilla on lighttpd or I would ask them for some assistance.

**Comment by mama21mama** [comment]
Solved > http://hubzilla.mamalibre.com.ar/admin/accounts

my > http://hubzilla.mamalibre.com.ar/admin/account_edit/1
