### ISSUE TITLE
Cannot comment/like some posts

### ISSUE THREAD

**Issue by dotevo** [redmatrix/hubzilla#546]
Hi,

I cannot comment and like some posts from diaspora. Even posts are public and I have that person in my friends list. Is it known issue?

Br,
Adam

**Comment by zotlabs** [comment]
What version of hubzilla are you running?

**Comment by dotevo** [comment]
I use http://hubzilla.site (1.12) https://hubzilla.site/siteinfo/json

**Comment by zotlabs** [comment]
We released 1.14 today - which contains a fix for Diaspora comments; when the original post was created on Hubzilla and was replied to by the original author. Don't know if that fits your circumstances, but I suspect hubzilla.site will be upgraded in the next couple of days. Most of our sites are pretty good about dating to new releases. If that bugfix doesn't fit your situation, we'd certainly appreciate a further description of the conversation structure (started on Diaspora or Hubzilla, and noting any successful replies on either side); so we can track down where the problem might be. Except for the bug which was just fixed and another involving complex interactions with hubzilla public forums, diaspora communications have been working reasonably well.

**Comment by zotlabs** [comment]
Looking at your initial report again, are comments vanishing (not getting delivered) or do you not get a comment box or a "like button" at all?

**Comment by dotevo** [comment]
There is no like button and comment box. Thanks I'll be waiting for an update.

**Comment by git-marijus** [comment]
@dotevo can you check if individual permissions for this contact are set?
You can see this if you go to /connections and click the pencil for the connection in question...

**Comment by dotevo** [comment]
https://postimg.org/image/ikvuevr9l/
But I've checked and the post is public.

**Comment by elvecio** [comment]
Are you sure that the person in  diaspora has accepted your _friendship_?
It seems to me a classic case that even acceptance of the contact did not take place, or has taken place with 'defect'.
Maybe is "some posts (that come) from diaspora" and not that he's in diaspora.

For the case, in the new version of hubzilla this thing has changed? it is still necessary that the person in diaspora accept the new friendship or not (also for public posts)?

**Comment by dotevo** [comment]
I'm not sure. When I'd moved to hubzilla, I added all friends from diaspora. But I watch some tags and I cannot comment public posts. I didnt have that problem on diaspora. If post is public than all people should can comment and like it.

**Comment by elvecio** [comment]
>  I didnt have that problem on diaspora.

Yes, I know, but, for what I know, here (hubzilla) we need that the d*person accepts our friendship (in diaspora).
Otherwise it does not even appear the boxes for comments in our hubzilla grid.

**Comment by dotevo** [comment]
Does it mean that in hubzilla the public posts are read-only?

**Comment by zotlabs** [comment]
In the Diaspora network, anybody may comment on public posts. I don't necessarily think this policy is a good idea, but we've implemented that here, for posts that originated on Diaspora. As far as I'm aware this is and has been working correctly.  I've had a quick look at the code and don't see anything that has changed in that regard in quite some time, so this bug is a puzzlement. 

For public posts that originate within the Hubzilla network, you must be given permission to comment. This typically requires a relationship between the post author and the commenter, although these permissions are configurable so you can in fact emulate the Diaspora model if you desire. 

However, I seem to recall there was an occasional issue with commenting on posts that arrived via the public stream (discover tab or public page), rather than in your personal stream. So I'm thinking that is what is happening here. It appears to be the result of these lines:

Zotlabs/Lib/ThreadStream.php::add_thread:L154

           elseif(($this->observer) && (! $item->is_commentable())) {
                if((array_key_exists('owner',$item->data)) && intval($item->data['owner']['abook_self']))
                     $item->set_commentable(perm_is_allowed($this->profile_owner,
                           $this->observer['xchan_hash'],'post_comments'));
                 else
                      $item->set_commentable(can_comment_on_post($this->observer['xchan_hash'],
                           $item->data));

I believe the check for abook_self might be in error when the source is a public stream. We probably need to also check if the item is owned locally by the sys channel (indicating a public stream post).

**Comment by elvecio** [comment]
public posts that come **from D***? 
Yes, if the person does not accept you as a friend.

Public post that come from hubzilla/zot ?  Not ( permissions  are very different in hubzilla) and it depends... as Mike explaining .

**Comment by zotlabs** [comment]
We typically use public forums here to provide open conversations. Diaspora sort of needs to have a public comment ability because it doesn't have forums/groups; only the ability to follow hashtags. It isn't that one model is right and the other is wrong. They are just different.

**Comment by dotevo** [comment]
What with ex. news stream? A bot can post some news but does not accept invitations. But I understand your point.

**Comment by elvecio** [comment]
> A bot can post some news but does not accept invitations.

Take  a look in 'permission scheme' - expert mode-  and you will understand better. In hubzilla you  can do a lot of things (and permissions schemes).

**Comment by zotlabs** [comment]
The policy issues are a distraction here. I'm trying to find the source of the issue. 

As it turns out, Diaspora top level posts aren't being posted to the public stream. This was in fact a bug. I'll have this sorted in a few minutes. So the public stream may have nothing to do with the problem.  So then we're left with @dotevo receiving a public post in his/her (I'm not certain of your gender) stream from a Diaspora person. It normally wouldn't have arrived in the stream unless his/her permissions allowed it. So far so good. 

What we don't know are the permissions for the Diaspora person. We set the comment_policy for Diaspora posts to allow comments if it is a public post. So if the comment arrives in your stream (not the public stream, but your own), and it is a public post, you should be allowed to comment - regardless of the Diaspora person's permissions. 

That's how it should work. If it isn't working, it indicates that a) the post isn't truly public, or b) you're trying to reply to a Diaspora commenter and not to a Diaspora top-level post, or c) something else is happening that we need to discover. 

The only candidate I can come up with for 'c' is if hubzilla.site attempted an upgrade to 1.14 and reverted; but the post arrived when the site was at something higher than 1.12. This would have left the post uncommentable as the 'comments_closed' date would be non-zero (we changed the definition of NULL_DATE in 1.14). So this is a possibility, but should only affect posts which arrived during the time the site was at a later version and should therefore be a transient event which will take care of itself when the upgrade completes.  

Given a, b, and c, I don't have enough information at hand to diagnose. I think we need the hubzilla.site admin involved or somebody with access to the site DB and/or logs (is that Arto? I can't remember).

**Comment by elvecio** [comment]
> is that Arto?

Yes, Arto.
So, if I understand correctly, now the comment box also appears with  people's post who have not yet accepted our friendship (for public posts from diaspora) in 1.14?
It has never worked before in this way, starting from the friendica times...

**Comment by zotlabs** [comment]
It has been working like this for quite some time. You're welcome to test it. I just did. I connected to a Diaspora account from Hubzilla, but didn't accept the friend request on the Diaspora side. Then sent a public post from Diaspora which would be delivered to the test server (since there is another Diaspora connection on it, which triggered public federation to that server). The post was received by the new Hubzilla connection and contains a comment box (even though that contact doesn't otherwise have comment permission).  There haven't been any code changes related to this behaviour in months (if not longer). So from my point of view, this is working correctly and normally, and I cannot duplicate the posted issue. So we're left with the three options mentioned in my last post. Either the post wasn't truly public, or it wasn't a Diaspora top-level post, or 'something weird and unexpected happened' due to hubzilla.site's configuration. 

I have patched dev (1.15) to deliver Diaspora top level posts to the public stream, but I don't have the public stream enabled on my test site; so cannot test that currently. Since it definitely wasn't working before and no top-level posts were being delivered to the public stream from Diaspora, any permissions issues related to the public stream have been ruled out as the source of the mentioned bug.

**Comment by elvecio** [comment]
I did this, and  not worked,  i don't have the comment-box, 
but is a 1.12+6dc7523 v.

**Comment by zotlabs** [comment]
Apologies, I stand corrected. I've looked through all the checkins. There was a change that went in on 5 September (after 1.12) which does affect the public comment behaviour. Prior to that public comments were only supported in the public stream and not between connections. 

So that changes this issue to 'fixed in 1.14'.

**Comment by dotevo** [comment]
I'm confirming. Works fine
