### ISSUE TITLE
Profile photo problem

### ISSUE THREAD

**Issue by ilu33** [redmatrix/hubzilla#561]
``` sql
INSERT INTO attach ( aid, uid, hash, creator, filename, filetype, filesize, revision, folder, os_storage, is_dir, content, created, edited, os_path, display_path, allow_cid, allow_gid, deny_cid, deny_gid )
                VALUES ( 4, 8, 'aef2c...12897c', 'I1d-aefx9...GzciqwA', 'Profile Photos', 'multipart/mixed', 0, 0, '', 1, '1', 'store/name/aef2...12897c', '2016-10-20 00:40:45', '2016-10-20 00:40:45', 'store/name/aef2...12897c', 'store/name/aef2...12897c', '', '', '' ) ; returned false
ERROR:  INSERT has more target columns than expressions
LINE 1: ...th, display_path, allow_cid, allow_gid, deny_cid, deny_gid )
                                                             ^
```

Patch will follow.

Edit:
This was the original error and something went wrong during patching that resulted in the aforementioned one: 

``` sql
INSERT INTO attach ( aid, uid, hash, creator, filename, filetype, filesize, revision, folder, os_storage, is_dir, content, created, edited, os_path, allow_cid, allow_gid, deny_cid, deny_gid )
                VALUES ( 6, 15, '73739467...O8PVEb4w', 'Profile Photos', 'multipart/mixed', 0, 0, '', 1, '1', 'store/name/73739467...89176dfb', '2016-10-11 19:07:47', '2016-10-11 19:07:47', 'store/name/73739467...f53e89176dfb', '', '', '', '' ) ; returned false
ERROR:  null value in column "display_path" violates not-null constraint
DETAIL:  Failing row contains (12, 6, 15, 73739467...f53e89176dfb, jIV1tGeIgiD3...SVNKaIGRe..., Profile Photos, multipart/mixed, 0, 0, , 0, 1, 0, 1, store/name/73739467...6b5ac35..., null, \x73746f72...39633537..., 2016-10-11 19:07:47, 2016-10-11 19:07:47, , , , ).
```

**Comment by zotlabs** [comment]
With all due respects I cannot locate that specific query in the sources. Are you sure you didn't edit this by hand to resolve one of the early postgres 'not null' issues? I find exactly 3 queries matching "INSERT INTO attach..." across the entire project and all have less than the twenty column arguments shown in the query issue report. 

This appears to be the query on line 1040 of include/attach.php but with os_path and display_path added to the column list; but only one '%s' appears to be have been added to the values list.

**Comment by ilu33** [comment]
We were still working on this and got sidetracked, that's why I wrote "Patch will follow" - meaning "please wait till we've figured this one out" :-)

**Comment by fsteinel** [comment]
pull request #562 fixes both Postgresql errors

**Comment by zotlabs** [comment]
I haven't yet merged as I cannot give it my full attention, but the additional fields should probably default to empty strings at this time. They are currently unused in code, and if they end up being set to the wrong thing it may be difficult to go back in later and fix it. The attempts to guess at what they might be weren't bad, but I'd personally rather that we set these all at once when we make use of the features that they were created for; as it isn't clear right now if we should be using absolute or relative paths and I noticed in one case a trailing slash was added, but not in the others; and this could be important. You're welcome to revise the pull request, otherwise I'll merge it in the next day or two and then reset all the defaults until we've settled on what they should be.
