### ISSUE TITLE
Not a valid email address during registration.

### ISSUE THREAD

**Issue by grouchysysadmin** [redmatrix/hubzilla#568]
On a clean installation, the registration page refuses sign up with the error, 'Not a valid email address'. 

The error happens regardless of the email address used. It even fails on test@example.com. All the emails I've tested are valid. I can run any type of diagnostic, if you can provide pointers as to where I should be looking. 

Edit: This installation files were pulled from git today using, git clone https://github.com/redmatrix/hubzilla.git

**Comment by zotlabs** [comment]
Here is the exact test that is being executed: 

    $h = substr($addr,strpos($addr,'@') + 1);

    if(($h) && (@dns_get_record($h, DNS_A + DNS_CNAME + DNS_PTR + DNS_MX) || filter_var($h, FILTER_VALIDATE_IP) )) {
        return true;
    }
    return false;


If this fails it usually indicates that your DNS resolution in not configured properly (dns_get_record() fails). You can either use an IP address or set a configuration variable  (system.disable_email_validation) in .htconfig.php to disable this check and proceed, but it will generally be counter-productive since Hubzilla is a decentralised system and very little will work without working DNS. We also use email verification to enable the account that is being created, so if for some reason you are unable to receive the generated verification email you won't be able to access the account. There are ways to bypass this as well, but the simplest way forward is to figure out why your DNS isn't resolving so you can use the system normally.

**Comment by grouchysysadmin** [comment]
Thank you. I'll do some testing and get back to you.

**Comment by grouchysysadmin** [comment]
Ok, so it appears that DNS is working. The various command line tools such as host, dig, etc all work. I've also tested PHP on the command line and through php-fpm. Here is my test and results. 

Test:
```
<?php
$result = dns_get_record("gmail.com", DNS_ANY, $authns, $addtl);
echo "Result = ";
print_r($result);
echo "Auth NS = ";
print_r($authns);
echo "Additional = ";
print_r($addtl);
?>
```
Results
```
Result = Array ( [0] => Array ( [host] => gmail.com [class] => IN [ttl] => 299 [type] => A [ip] => 216.58.216.197 ) [1] => Array ( [host] => gmail.com [class] => IN [ttl] => 299 [type] => AAAA [ipv6] => 2607:f8b0:4009:808::2005 ) [2] => Array ( [host] => gmail.com [class] => IN [ttl] => 3599 [type] => MX [pri] => 30 [target] => alt3.gmail-smtp-in.l.google.com ) [3] => Array ( [host] => gmail.com [class] => IN [ttl] => 3599 [type] => MX [pri] => 20 [target] => alt2.gmail-smtp-in.l.google.com ) [4] => Array ( [host] => gmail.com [class] => IN [ttl] => 3599 [type] => MX [pri] => 10 [target] => alt1.gmail-smtp-in.l.google.com ) [5] => Array ( [host] => gmail.com [class] => IN [ttl] => 21599 [type] => NS [target] => ns3.google.com ) [6] => Array ( [host] => gmail.com [class] => IN [ttl] => 3599 [type] => MX [pri] => 5 [target] => gmail-smtp-in.l.google.com ) [7] => Array ( [host] => gmail.com [class] => IN [ttl] => 21599 [type] => NS [target] => ns4.google.com ) [8] => Array ( [host] => gmail.com [class] => IN [ttl] => 21599 [type] => NS [target] => ns2.google.com ) [9] => Array ( [host] => gmail.com [class] => IN [ttl] => 3599 [type] => MX [pri] => 40 [target] => alt4.gmail-smtp-in.l.google.com ) [10] => Array ( [host] => gmail.com [class] => IN [ttl] => 21599 [type] => NS [target] => ns1.google.com ) [11] => Array ( [host] => gmail.com [class] => IN [ttl] => 59 [type] => SOA [mname] => ns3.google.com [rname] => dns-admin.google.com [serial] => 137187875 [refresh] => 900 [retry] => 900 [expire] => 1800 [minimum-ttl] => 60 ) [12] => Array ( [host] => gmail.com [class] => IN [ttl] => 299 [type] => TXT [txt] => v=spf1 redirect=_spf.google.com [entries] => Array ( [0] => v=spf1 redirect=_spf.google.com ) ) ) Auth NS = Additional = 
```

Is there a way to test the DNS resolution of hubzilla specifically? I'm not sure how to use the code you posted above.

**Comment by grouchysysadmin** [comment]
Another note. On my first install I did the database set up by hand. I've just tried to do a clean install using the web wizard to install the database and it fails with this error. 
```
Warning: dns_get_record(): DNS Query failed in /public_html/include/dba/dba_driver.php on line 172

Warning: mysqli::mysqli(): (HY000/2002): Operation now in progress in /public_html/include/dba/dba_mysqli.php on line 9
CRITICAL: DB not connected.
```
I'm not sure why since the database server is an IP address and not a domain name. Also, all the setup pages take a long time to load. It really does seem like a DNS issue, but as far as I can tell DNS works perfectly. Any other suggestions?

**Comment by zotlabs** [comment]
As for the installation error, we check DNS before checking the IP, and the warning is actually being emitted by dns_get_record() internally to the function. As far as testing, I would just create a simple test script with

    <?php
    $server = 'fill this in';
    print_r(dns_get_record($server, DNS_A + DNS_CNAME + DNS_PTR));

(In the email validation we add DNS_MX, but since it is failing for you on install where we aren't checking for MX let's keep it simple).

There are some comments on the web related to seeing issues on BSD and Mac so it might be useful to know what platform you're running, and I don't think there will be any issue with IPV6 but that could also be useful knowledge if you don't have any IPV4 services locally. Otherwise, this is just a PHP system function that has traditionally been working satisfactorily for us. I do recall somebody else had a problem with it a few years back but they worked it out and unfortunately I can't locate that conversation now.

**Comment by grouchysysadmin** [comment]
Hello, 

That does appear to be the issue. This code fails.  

```
<?php
$server = 'google.com';
print_r(dns_get_record($server, DNS_A + DNS_CNAME + DNS_PTR));
```

I receive an error of: PHP Warning:  dns_get_record(): DNS Query failed in /public_html/dns-test.php on line 3

Oddly enough, I can run this function interactively and it works fine. 

```
# php -a
Interactive mode enabled

php > print_r(dns_get_record('google.com'));
Array
(
    [0] => Array
        (
            [host] => google.com
            [class] => IN
            [ttl] => 299
            [type] => A
            [ip] => 216.58.216.78
        )
SNIP
```

The server setup is FreeBSD 10 using PHP 5.6. I can also test 7.0 if that would make a difference.

**Comment by zotlabs** [comment]
That does seem to imply that it is a system related or system dependent issue of some form and not an actual bug in the hubzilla code.

**Comment by grouchysysadmin** [comment]
It would appear to be a PHP/OS incompatibility. From what I can tell, the dns_get_record function is implemented on FreeBSD, but it does not work with all record types. 

I was able to make it work with these record types. 
DNS_A
DNS_NS
DNS_AAAA
DNS_MX
DNS_SOA
DNS_TXT

It fails on the following types.  
DNS_ANY
DNS_ALL
DNS_CNAME
DNS_PTR
DNS_SRV
DNS_HINFO
DNS_NAPTR

Including any one of the failed types with a working type causes the entire function to fail.  

Looking at your first example, does the DNS_CNAME, and DNS_PTR values need to be there? Removing them would in theory allow this to work. If you could tell me where to comment it out, I'd be happy to try.

**Comment by zotlabs** [comment]
There are two places in include/network.php (one for validating domains and the other for emails). Otherwise those are the only places (4 occurrences) I know of.

**Comment by grouchysysadmin** [comment]
Ahh, I missed the second one in network.php. Even with all four commented out, the web based installer fails at the database section. However, I can do the installation manually. Taking out the DNS_CNAME and DNS_PTR from the network.php seems to be enough to resolve the invalid email during user registration. 

Is doing that safe? What are the repercussions from not checking CNAME and PTR records?

**Comment by zotlabs** [comment]
What I've just done is consolidated all the checking into one function and allow you to bypass it by setting 

\App::$config['system']['do_not_check_dns'] = 1;

This is available in the dev branch right now. 

We mostly do these checks so that we don't waste resources trying to communicate with names people enter that are clearly non-existent or bogus. You can end up with these bogus entries in your DB and they will just suck up resources. Since DNS apparently works on your system but dns_get_record() doesn't, I'll let you decide if that's what you want to do.

There are a lot of sites on the internet with aliases (PTR records) but no matching A records.

**Comment by grouchysysadmin** [comment]
Awesome. I'll pull the dev branch tomorrow and test it. 

Thank you.

**Comment by grouchysysadmin** [comment]
Here are the results of testing the dev branch. 

The database DNS errors during the web install are still present. I can install using an IP for the database server now, but trying a DNS name fails. Also, it appears not to respect the /etc/hosts file settings. 

I can do a manual install and set the App::$config['system']['do_not_check_dns'] = 1; configuration. If I do that, the registration system works.

I have to correct my earlier test. The 'DNS_ANY' parameter does work on FreeBSD. Is it possible to use that to run at least partial DNS checks? The idea of higher resource usage, or the potential for fake data being added to the database is worrisome.  

Thank you for all your help on this.

**Comment by zotlabs** [comment]
DNS_ANY might be workable. It's not perfect, but either is the domain check - because there's no guarantee that a machine is actually functioning at the IP address returned. So I'm OK if you want to submit that as a patch.

Installation is slightly trickier because there's no .htconfig.php to set your choice. Last night I did provide for a file .htpreconfig.php which could be loaded before installation if you require special installation settings such as this. We've needed this for other reasons so the effort wouldn't be wasted by converting the check to DNS_ANY.

**Comment by grouchysysadmin** [comment]
Out of curiosity, why dns_get_record instead of gethostbyname, or gethostbyaddr? Does the solution have to be PHP only, or could it incorporate server tools such as host or possible curl?

Either way, I'll do what I can.

**Comment by zotlabs** [comment]
We started off with gethostbyname (years ago) and there were issues. If I recall it was a severe performance issue on Windows.  dns_get_record didn't have these issues so we started using that instead.

Using host or curl assumes you have a *nix server of some kind, and we do have folks running Windows.

You can create a plugin to use gethostbyname or dig over tor over bash if that's what you want. We're pretty easy. But I think the default behaviour should probably be to continue using dns_get_record(); which works just fine for everybody else.

**Comment by grouchysysadmin** [comment]
Understood. I'll try and learn how to make z_dns_check work with DNS_ANY.

Thank you for all your help.
