### ISSUE TITLE
move bug report to end of apps

### ISSUE THREAD

**Issue by encyclomundi** [redmatrix/hubzilla#588]
I agree with alphabetical ordering of the apps, but the  very first thing someone sees on /apps is the Bug Report. I feel the apps page is a _shiny_ feature and can help quickly show the scope of the project, plus it follows the UI feel of tablets and phones. Moving Bug Report to the end removes an unneeded distraction.

**Comment by zotlabs** [comment]
Maybe we should call it "Issues" ; though there's no guarantee how it might turn out in other languages.

**Comment by zotlabs** [comment]
"Report bug", "Report issue" would also move it a bit further away from the edge.

**Comment by encyclomundi** [comment]
Both of those work for me. Maybe Report bug?

**Comment by zotlabs** [comment]
Basically fixed but this highlighted another problem. It's fixed going forward. You will now have two apps (Bug Report and Report Bug) in your personal channel apps because we give you a private copy of all the system apps to edit and delete as you see fit. So just check that you have 'Report Bug' and if so, you can safely delete 'Bug Report'. Now to ponder how to clean up this mess automatically...
