### ISSUE TITLE
Message uid missing in api post response

### ISSUE THREAD

**Issue by Flashwalker** [redmatrix/hubzilla#638]
Don't know bug or feature, but post response to `/api/statuses/update` doesn't contain **message_id** (muid), so can't get url for actually posted status. There is only **id**. Is there a way to display post page by **id**?

**Comment by zotlabs** [comment]
The Twitter API specification does not mention either message_id or muid. It only refers to id or id_str (which is id converted to a string). We provide id, which is suitable for inclusion in the Twitter API call api/statuses/show.

Note that hubzilla not provide a complete implementation of the Twitter API - only what is necessary to provide minimal functionality with many third-party clients. We are converting internally to the Zot API, which is still under development; although quite a bit of functionality is currently in a working state.

**Comment by Flashwalker** [comment]
But /api/statuses/show returns muid, why not to have it in /api/statuses/update to?
You wouldn't include it?

**Comment by zotlabs** [comment]
The Twitter API plugin has a number of duplicated code blocks related to formatting of items which should probably be consolidated; as it leads to inconsistencies such as this.  Several of these have been here since the Twitter API was first added to the project repository in 2011. 

Now "fixed" in dev, by forcing api_statuses_update to use the generic item format response, which includes the unsupported and undocumented mid field; and is the same call that was used to format the statuses/show response.

**Comment by Flashwalker** [comment]
Nice!  
Let there be a smooth road to this release!
