### ISSUE TITLE
 Feature request:  caption for "external cron"-Plugin to complete

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#657]
I suggest caption for "external cron"-Plugin to complete, namely thus 

> Use external server or service to run Hubzilla-poller/cron regularly

The addition Hubzilla-/cron can help for English-Beginners to differentiate between `poller Interviewer` and `cron job`. S. also ["external cron"-Plugin](https://hub.freecommunication.org/display/e6e936c0d0e378fc09027029483bb7b80855afb761056394f304db3b3061b1ef@hubz.gacrux.uberspace.de) -support-request.

**Comment by zotlabs** [comment]
Changed to 'background tasks' as we do not directly invoke the poller task any more and cron will only have meaning to people who are familiar with Unix (and its derivatives).  No doubt this will also have translation issues; in which case please re-open as a task to auto translate code, since this is taken from a comment in the code and is not a constant string which can be easily provided for translation.
