### ISSUE TITLE
Move file in dav, permissions don't follow

### ISSUE THREAD

**Issue by solstag** [redmatrix/hubzilla#680]
When moving a folder or a file using DAV, the folder or file in the new location does not retain the original's permissions. I suppose it would be expected that it did retain the permissions.

**Comment by zotlabs** [comment]
We have a function to move photos which preserves permissions. DAV does not have an atomic move operation. DAV clients perform this operation by copy and delete. DAV clients are also unaware of hubzilla permissions. There is an ACL ability in DAV but it is currently not compatible with Hubzilla due to nomadic identity. I've been looking at various ways of resolving this but so far don't have a workable model. Even if I did, it would rely on a client that moves a file to perform the ACL setting operation afterward. That is a client function, and I don't believe is required by the DAV specification. 

The other option is to provide a web-based move operation for files like we did for photos. That may be all anybody can do on the short term. You would be welcome to explore this operation - it would be mostly cut and paste.

**Comment by solstag** [comment]
Hm, I'm not claiming to understand anything about DAV, but Sabredav's documentation mentions a "MOVE" function in the RFC it claims to implement <https://tools.ietf.org/html/rfc4918#page-56>. Isn't that what clients use to move stuff? (Ok, I wouldn't be surprised if it isn't). Because then it would indeed be possible to hook the permissions move on top of that, not?

Another thought would be to have those permissions based on the hash, which we apparently do keep up with. Or at least I am under the impression that when I move a file any posts which embed it continue to embed it. That would force copies of a file to have the same permissions, and could probably complicate things enough to be prohibitive, but could be more acceptable than webdav doesn't honor permissions. Just throwing thoughts away.

In any case, if I find the time to work on it, I shall take a look at the function that moves photos and try to bring it to files.

Thanks! =)

**Comment by zotlabs** [comment]
This may be true, but I'm not aware of where in the Sabre programming interface this is implemented. The only such interface I'm aware of is a rename of a file in the same folder (which we implement). I will have a deeper look though I'm spread pretty thin at the moment.

**Comment by zotlabs** [comment]
I've found the interface (vendor/dav/lib/DAV/IMoveTarget.php) and I believe we can implement this. I cannot give you a time estimate.
