### ISSUE TITLE
markdown <URL> formatting seems broken

### ISSUE THREAD

**Issue by dvs1** [redmatrix/hubzilla#752]
Using the wiki feature on https://hubchart-tarine.rhcloud.com/hub.jsp?hubFqdn=hubzilla.top:
If I use `<>` to try and make a link hot, i.e. `<https://github.com/redmatrix/hubzilla/>`
then it will seemingly work after I save it;
however, if I reload the page, then the links will be missing.

**Comment by zotlabs** [comment]
I don't see any wiki feature on hubchart-tarine.rhcloud.com and it is a statistics site running in Java if I recall. So that would not be a hubzilla bug.

If you are actually referring to a wiki that is provided on hubzilla.top,  that is a different story. 

Using angle brackets to make a link "hot" is not supported by the markdown language to my knowledge - and even if it were, Hubzilla would likely be forced to strip it as part of its XSS filtering procedure since markdown can contain arbitrary HTML. The syntax you've presented here is not legal HTML either.  

https://daringfireball.net/projects/markdown/syntax#link

If you have evidence to the contrary, that angle bracket link syntax is supported in the official definition of the markdown language, please provide a pointer to the appropriate reference. I have not seen this used in any markdown specification (official or otherwise).

**Comment by dvs1** [comment]
Yes, I was referring to hubzilla.top

I guess that was a modification added by SourceForge.

Since I don't like my links cold, is there any way to heat them up? ;-]

`[https://github.com/redmatrix/hubzilla/](https://github.com/redmatrix/hubzilla/)` is suboptimal.

**Comment by dvs1** [comment]
Correction: https://daringfireball.net/projects/markdown/syntax#autolink

**Comment by zotlabs** [comment]
OK, I stand corrected. Then the only question is how to fix it without introducing a security hole. You've no idea the work we went through to purify markdown. If it is your own site you can work around it by giving yourself code rights (the ability to enter unpurified code). Otherwise Zotlabs/Lib/MarkdownSoap.php is where we rip the text apart and purify it so that you can't sneak in any malicious javascript. If it contains angle brackets and isn't in a code block and isn't valid HTML it is removed by HTMLPurifier. So one would need to detect angle brackets surrounding a legal link with a "safe" url scheme and no other : characters (or hex equivalents) except the one delineating the valid scheme and then escape it before purification - and put it back afterward.

**Comment by dvs1** [comment]
Thanks. 😎
