### ISSUE TITLE
parser defaced cover photo through german umlauts

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#779]
parser defaced cover photo through german umlauts - s. screenshot. Correct string is 
> Wünsch dir was! Crowdfunding-Torrent - hier geht es schwerpunktmäßig um die Verwirklichung von fehlenden Hubzilla-Features

![miscarries_cover_photo1](https://cloud.githubusercontent.com/assets/3226308/26073746/f7b11538-39af-11e7-97fb-1b9b084ae3a6.png)

**Comment by zotlabs** [comment]
Unable to duplicate. This is likely an incorrect database collation. Please contact your site administrator.

**Comment by AlfredSK** [comment]
Hello,
I'm using utf8mb4_unicode_ci as database collation. Some fields have keys that are too long for utf8mb4. So, the conversion is failing and they are still on utf8_general. I think that causes the issue.

**Comment by zotlabs** [comment]
From my understanding, utf-8 should be stored correctly using either collation, but the indexes will only be able to index 191 chars if it's stored in utf8mb4, the rest of the string won't be indexed. I may be wrong, but that's my recollection. Some emojis and a few Chinese characters aren't stored correctly in utf8 (the hubzilla default collation). This has been fixed in development but may not be released generally for several more months and mostly affects the ability to use emojis in channel names (currently unsupported).  

I believe the field we're using here is the profile.name - though there is some synchronisation with channel.channel_name and xchan.xchan_name if any of these change. It seems like a completely different collation (perhaps iso8859-1) is being used for at least one of these; but since I can't duplicate the issue on my site using the hubzilla default database structure (or the newer experimental database structure which is utf8mb4) I don't believe it is a code issue or a bug that can be fixed at the project level. It appears to be site specific.
