### ISSUE TITLE
not existing block in switch-statement eliminated this statement complete

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#785]
when the block "name-block" not exist, than failed switch-statement complete. Nothing will be displayed, default-branch will be not executed. Suggest: one hint "Block block123 not found!", when the block "name-block" not exist. Hubzilla-Version 2.4RC
![1](https://cloud.githubusercontent.com/assets/3226308/26186165/d6a92e2a-3b8f-11e7-8958-48265717c9aa.png)

**Comment by zotlabs** [comment]
Comanche is working correctly. The contents of "name-block" have been inserted correctly where the layout specification said to insert those contents. If a specific layout element cannot be found, the inserted contents are set to nil (an empty string). Comanche has no error messages. This is by design. Site administrators can remove widgets and plugins and themes that you've specified in a layout and we have to be able to continue on no matter what happens. Anything that is requested but not found is set to nil and execution continues.
