### ISSUE TITLE
nice-to-have: copy und paste feature for page, layout and block items

### ISSUE THREAD

**Issue by HappyPony** [redmatrix/hubzilla#789]
for one content management system are copy und paste for page, layout and block items features nice-to-have and natural, respectively.

**Comment by git-marijus** [comment]
Not sure what you mean with 
> copy and paste for page, layout and block items

Can you explain?

**Comment by HappyPony** [comment]
I thought about this functionality, 

![what_i_mean_copy_past](https://cloud.githubusercontent.com/assets/3226308/26390507/1f085398-405f-11e7-8f62-3b6240536d7e.png)

whereby by click at `header item` HI on top may one menu offert, where I can create one `page `or `layout `or `block `or `menu`. Very helpful for example in menu item Info are Infos about them, whether and where are layout, menu and block in any page in use. Under `Visibility Infos` be able Infos from ACL to display.

**Comment by git-marijus** [comment]
We try to keep blocks, menus, layouts and pages separate because they all have a different purpose. Therefor we don't have the ability to add e.g. layouts in the block tool. You have to use the layout tool for that.

We provide ACL infos for items which have/can have an ACL (pages and menu items) already. You just need to click the lock icon.

I don't think we can easily track where layouts, blocks or menus are used the way the webpages app works at the moment. This would probably take a major rewrite of the app to work.

I will close this issue for now. Please feel free to open a separate issue for the last feature request if you feel this is needed. I am afraid it won't happen anytime soon though...
