### ISSUE TITLE
Dev since 2.58 i think SQL General error: 1364

### ISSUE THREAD

**Issue by albigro** [redmatrix/hubzilla#828]
Hat an error
When making a post got a System Error popup.
Post was not stored, nothing new in activity anymore
in the log, the message was
SQLSTATE[HY000]: General error: 1364 Field 'diaspora_meta' doesn't have a default value
I just changed the table for now:
ALTER TABLE `item` CHANGE `diaspora_meta` `diaspora_meta` mediumtext NOT NULL DEFAULT '';
I have nothing to do with coding, but it worked for me (don't think its the best solution).
Debian deb9u2 php-7.0 with fpm mariadb (all debian default atm)

**Comment by git-marijus** [comment]
What version of mariadb do you use?

**Comment by albigro** [comment]
I started using hubzilla 2015 +- (it replaced  Friendica) and using devel Version from git since 2016 i think.
Btw im so happy with it, thanks a lot, 4 all your work!
mariadb-server-10.2.6
Version: 10.2.6+maria~stretch
mariadb-server-core-10.2
Version: 10.2.6+maria~stretch

**Comment by git-marijus** [comment]
That is wierd. I myself use mariadb v10.1 and don't see this issue...
Anyway, this has been changed recently because MySql v5.7 complained that text fields must NOT have a default value.

**Comment by snarfed** [comment]
this hit me too. is there a recommended workaround? don't use mysql 5.7+ until hubzilla is updated to always provide explicit values for text fields?

**Comment by snarfed** [comment]
i'm using mysql 5.7, so i couldn't add a default value like @albigro did. i made it nullable instead, which works:

```sql
ALTER TABLE item CHANGE diaspora_meta diaspora_meta mediumtext NULL;
```

**Comment by zotlabs** [comment]
It's a bit of a catch-22 because we removed everything in the code that uses diaspora_meta. It has been deprecated for  a year or more.  We didn't actually remove the field from the database schema because identity clones can send that in a content mirror packet. It wasn't until sites started to upgrade their SQL servers that this became an issue. The last bits of the code which used it "if it existed" were removed a little over a month ago. So now we are finally able to move forward with ridding ourselves of this thing.

If you're running a recent release you can just remove that column from the database as we stopped using it long ago.

The action items are
1.  adjust the content mirroring scripts to ignore that field if they see it on an inbound packet so there aren't any errors cloning content. (I'm doing this now.)
2. remove the diaspora_meta column from the database schema files.
3. Provide a DB upgrade to drop the column if it exists.

**Comment by zotlabs** [comment]
Should be completed upstream. 

[master 7386fa5] remove column item.diaspora_meta, action items 2 and 3 of hubzilla issue #828

I believe this issue can be closed once this work has been merged.
