### ISSUE TITLE
The-federation.info register route being spammed

### ISSUE THREAD

**Issue by jaywink** [redmatrix/hubzilla#831]
I've had to firewall block already 3 hubzilla instances, macgirvin.com, albigro.com and hub.somatom.com, due to DoS of my server where the-federation.info is set up. Basically constant register route calling, at least 1/s.

I assume this is set somehow in the Diaspora plugin of Hubzilla, which might be malfunctioning with some kind of crazy loop?

![hubzilla](https://user-images.githubusercontent.com/1174866/28328704-0ac972f6-6bf0-11e7-9279-b4e00c898efb.png)

I'll check periodically if the traffic stops.

**Comment by zotlabs** [comment]
I've found an issue in hubzilla/red where the cron_daily callback was being executed more than once a day - up to once every cron interval (15 minutes if you use the recommendations).  I will also change the register callback to happen on cron_weekly events; it was done more frequently to trigger a daily refresh of any changes in the followed tags list by site members, but you've indicated previously this may be unnecessary. 

I found log events on my site consistent with this explanation. Let me know if you saw it from my site at the same high rate, because I don't see log events to back that up. 

This should fix macgirvin.com and somatom.com as soon as Mario picks up the changes. albigro.com appears to be seriously mis-configured. Will try to contact the owner.

**Comment by git-marijus** [comment]
@jaywink do you still see this issue?

**Comment by git-marijus** [comment]
I finally got to review my server logs (this loop also DoS'ed my box) and i can confirm the loop.

**Comment by git-marijus** [comment]
@zotlabs i think i found the issue:
https://github.com/redmatrix/hubzilla-addons/blob/dev/statistics/statistics.php#L60
`statistics => total_users` never got set in my config. I got a `statistics_json => total_users` though which must be there from ancient times (current master).

I think we need to look for `system => channels_total_stat` here.

**Comment by git-marijus** [comment]
Here is my fix: https://github.com/redmatrix/hubzilla-addons/commit/76510670e8a5e1312c43694794fdd2c81b616c11

**Comment by git-marijus** [comment]
@jaywink i think you can now safely unblock hub.somaton.com again

**Comment by jaywink** [comment]
I've removed all the IP blocks and will monitor the logs. Thanks all!
