### ISSUE TITLE
wiki: provide nav element to return to top level

### ISSUE THREAD

**Issue by zotlabs** [redmatrix/hubzilla#854]
Within a wiki, there is no easy navigation to the top level wiki list. One can use the corresponding wiki app, but if this is not provided it could be useful for a button or link to return to the top.

**Comment by git-marijus** [comment]
Yeah... This is defenitely needed somewhere. I have not figured out the best place for this since i would not like it to be on the 'page' where the pages widget is.
I think this will be fixed once we will find a place to display the app name. This could then be used to always get to the 'toplevel' app level...
