### ISSUE TITLE
channel page cover photo  (navbar) interactions

### ISSUE THREAD

**Issue by zotlabs** [redmatrix/hubzilla#866]
Opening this as a reminder because it represents a few related issues. When a channel has a cover photo installed, the links on the navbar aren't functional until the cover photo has been "closed/moved". This is a usability issue because one of the first actions typically is clicking something in the navbar.

So the navbar should probably be hidden with the text, or somehow made to function when the cover photo is being displayed. 

I would do something about this, but leaving in an issue because I believe "linked scrollbar effects" have been deprecated in Firefox and at some point we will need to re-design the cover photo interaction. Dealing with the navbar should be a subset of that effort.

**Comment by git-marijus** [comment]
IIRC the cover photo itself does not use linked scrollbar effects. It's the fading in of content which does.
We fade out the content bcause otherwise the cover photo is loosing focus.

Making the navbar buttons functional if the cover-photo is visible is probably trivial. I think though that it is weird to click a button and then the button does something and at the same time the screen scrolls up - thats why we dedicated the first click to scroll up the cover-photo. We might need to fade the buttons aswell to make it clear that they are not functional at this point.

> I believe "linked scrollbar effects" have been deprecated in Firefox and at some point we will need to re-design the cover photo interaction.

Well yeah, they warn about it because they can't deal with it very well. It works much better again in the current beta though where they use a new rendering engine...

**Comment by zotlabs** [comment]
I've got something I think is workable.
