### ISSUE TITLE
Missing left menu in Channel settings for Connection Default Permission and Channel Sources

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/hubzilla#893]
The other items on the channel Settings page appear in the left Settings menu when clicking an item, but this does not happen for Connection Default Permission and Channel Sources, forcing a member to use the brower's back button.

Suggested solution: adding these two the left Settings menu.

**Comment by zotlabs** [comment]
The contents of the pdl layout are determined by the module. Connection default Permissions actually is invoked in the Connedit module. It could make sense to separate this into its own module at the cost of some code duplication as the existence of this "unusual" operating mode turns that module into spaghetti in a few places. Otherwise adding the widgets will just create more spaghetti. Channel sources is  a standalone module so can be fixed by simply adding the settings_menu widget to its default layout. I've just done this second bit.

**Comment by zotlabs** [comment]
This should be resolved.

**Comment by HaakonME** [comment]
Channels sources is in the settings menu now, thanks.
