### ISSUE TITLE
Diaspoara post: Only first image visible

### ISSUE THREAD

**Issue by hfroese** [redmatrix/hubzilla#973]
A diaspora post with multiple images is broken on Hubzilla. The first image is visible in network stream only,

![images](https://user-images.githubusercontent.com/1968490/35724751-2d4df904-07ff-11e8-8b47-dfcffaa4faf2.png)

**Comment by zotlabs** [comment]
Unable to duplicate; either with uploaded photos or linked photos.

**Comment by elvecio** [comment]
I remember very well this bug since  friendica's times...
But I did a test today  and it work well  now, at least using 3 jpeg files  in diaspora upload.

I don't know about >3 or png or others..

**Comment by hfroese** [comment]
I'll post a link to a post if this happens again. Usually this user posts multiple images all two or three days.

**Comment by hfroese** [comment]
Ok - here we go.

Original post: https://sechat.org/posts/3456702

Same post on Hubzilla:

![20180111-1002](https://user-images.githubusercontent.com/1968490/36071672-ba6b883c-0f12-11e8-93a4-0f7229f93502.jpg)

and source:

![20180111-1000](https://user-images.githubusercontent.com/1968490/36071676-cdbe4abe-0f12-11e8-96e8-a814ce067e58.jpg)

**Comment by zotlabs** [comment]
Difficult problem. Basically the photo isn't being served in HTTPS and we are being blocked from accessing the photo by proxy (mod_sslify). I suspect the server in this case is sniffing the header from our HTTPS image proxy and finding something it doesn't like. The server at http://www.fotos.goehde.com returns:

HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 0
Connection: keep-alive
Keep-Alive: timeout=15
Date: Sun, 11 Feb 2018 19:36:19 GMT
Server: Apache
X-Powered-By: PHP/5.5.38


...which is not an image. 

Ironically this image would work perfectly if the source image was https but since it is http it would be blocked from being viewed by your browser, and our attempt to get around this restriction by proxying the photo through an https connection on your site is being blocked by the original content server.

I don't know that there is much we can do except ask the person to turn off blocking. If the block is according to user-agent string (a common method for blocking photos) we might be able to provide a different user-agent in our ssl proxy.

**Comment by hfroese** [comment]
okay - I see. The first image is **uploaded** at sechat.org but the others are served via camo server from http://www.fotos.goehde.com/start.php?vb=995019 and http://www.fotos.goehde.com/start.php?vb=995021

**Comment by zotlabs** [comment]
Correct. I cannot easily determine what software is running at www.fotos.goehde.com so it is a bit difficult to determine what blocking mechanisms may be in use and what is triggering it. The Diaspora camo server is apparently allowed to access the photos, but the Hubzilla equivalent is not. We provide a user-agent string of 

Mozilla/5.0 (compatible; zot)

I also cannot easily determine what user-agent the Diaspora camo server is providing. I have no problems adding 'Mozilla' compatibility to the user-agent (most everybody does), but I think there would be ethical issues with trying to match the Diaspora camo implementation just to get around somebody's access block. We would effectively be trying to bypass their web server security.

**Comment by hfroese** [comment]
okay. So this is a one posters issue only and I think there is no need to fix it. 
Thanks for your assistance Mike.
